import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, isAbsolute, join, relative, resolve } from "node:path"

import type { VoyantConfig } from "@voyantjs/core/config"

import {
  type AdminEntryScanResult,
  DEFAULT_GENERATED_RELATIVE_PATH,
  scanAdminEntries,
} from "../lib/admin-entries.js"
import { getBooleanFlag, getStringFlag, parseArgs } from "../lib/args.js"
import { loadVoyantConfigFile, resolveConfigPath } from "../lib/config-loader.js"
import type { CommandContext, CommandResult } from "../types.js"

/**
 * `voyant admin generate [--config <path>] [--out <file>] [--check]`
 *
 * Manifest-driven admin composition (packaged-admin RFC §4.1): for every
 * module in voyant.config.*, derive its `<module>-ui/admin` entry (or the
 * module's `package.json#voyant.adminEntry` override), verify the entry via
 * package.json inspection only, and emit a committed file of static imports:
 *
 * ```ts
 * import { createPromotionsAdminExtension } from "@voyantjs/promotions-ui/admin"
 * export const generatedAdminExtensionFactories = { ... } as const
 * ```
 *
 * Factories — not instances — so hosts can pass localized labels/icons.
 *
 * `--check` writes nothing and exits 1 when the committed file is missing or
 * differs from what would be generated (CI drift gate).
 */
export async function adminGenerateCommand(ctx: CommandContext): Promise<CommandResult> {
  const args = parseArgs(ctx.argv)
  const configFlag = getStringFlag(args, "config")
  const outFlag = getStringFlag(args, "out")
  const check = getBooleanFlag(args, "check")

  const configPath = resolveConfigPath({ path: configFlag, cwd: ctx.cwd })
  if (!configPath) {
    ctx.stderr(
      configFlag
        ? `No voyant config found at ${configFlag}\n`
        : `No voyant.config.* found in ${ctx.cwd} or any parent directory.\n`,
    )
    return 1
  }

  let config: VoyantConfig
  try {
    const loaded = await loadVoyantConfigFile<VoyantConfig>(configPath)
    config = loaded.config
  } catch (err) {
    ctx.stderr(`${err instanceof Error ? err.message : String(err)}\n`)
    return 1
  }

  const configDir = dirname(configPath)
  const modules = config.modules ?? []
  const results = scanAdminEntries(modules, configDir)

  for (const result of results) {
    if (result.status === "found" && !result.note) continue
    ctx.stderr(`[admin-generate] ${describeResult(result)}\n`)
  }

  const found = results.filter((result) => result.status === "found")
  const content = renderGeneratedFile(found)

  const outPath = outFlag
    ? isAbsolute(outFlag)
      ? outFlag
      : resolve(ctx.cwd, outFlag)
    : join(configDir, DEFAULT_GENERATED_RELATIVE_PATH)
  const printablePath = relative(ctx.cwd, outPath) || outPath

  if (check) {
    const existing = existsSync(outPath) ? readFileSync(outPath, "utf8") : null
    if (existing === content) {
      ctx.stdout(
        `[admin-generate] ${modules.length} modules, ${found.length} admin entries, ${printablePath} is up to date\n`,
      )
      return 0
    }
    ctx.stderr(
      existing === null
        ? `[admin-generate] ${printablePath} is missing — run \`voyant admin generate\`\n`
        : `[admin-generate] ${printablePath} is out of date — run \`voyant admin generate\`\n`,
    )
    return 1
  }

  mkdirSync(dirname(outPath), { recursive: true })
  writeFileSync(outPath, content)
  ctx.stdout(
    `[admin-generate] ${modules.length} modules, ${found.length} admin entries, wrote ${printablePath}\n`,
  )
  return 0
}

function describeResult(result: AdminEntryScanResult): string {
  switch (result.status) {
    case "found":
      return `note: ${result.moduleName} — ${result.note}`
    case "missing-export":
      return `warning: skipped ${result.moduleName} — ${result.note}`
    case "module-unresolved":
    case "not-a-package":
      return `note: skipped ${result.moduleName} — ${result.note}`
    default:
      return `note: ${result.moduleName} — ${result.note} (no admin entry)`
  }
}

/**
 * Render the committed composition file. Deterministic output (manifest
 * order) so `--check` is a pure string comparison.
 */
export function renderGeneratedFile(found: ReadonlyArray<AdminEntryScanResult>): string {
  const header = [
    "// GENERATED by voyant admin generate — do not edit.",
    "// Recreate after changing the modules list in voyant.config.*:",
    "//   voyant admin generate",
    "",
  ]

  const imports = found.map((entry) => `import { ${entry.exportName} } from "${entry.importSpec}"`)

  const body = [
    "/**",
    " * Admin extension factories keyed by module domain. Factories, not",
    " * instances — hosts call each with localized labels/icons before",
    " * registering the result.",
    " */",
    "export const generatedAdminExtensionFactories = {",
    ...found.map((entry) => `  ${entry.camel}: ${entry.exportName},`),
    "} as const",
    "",
  ]

  return [...header, ...(imports.length > 0 ? [...imports, ""] : []), ...body].join("\n")
}
