import { join } from "node:path"

/**
 * Static analysis + rendering for `voyant admin generate --routes` and the
 * admin doctor's destination-parity finding (packaged-admin RFC §4.2 / §4.7).
 *
 * Everything here is pure source-text scanning — no admin entry is ever
 * imported or executed. The scanners are deliberately convention-bound: they
 * understand the `defineAdminExtension({ routes: [...] })` shape and the
 * `declare module "@voyantjs/admin"` destination declarations the `*-react`
 * packages actually write, resolving option-destructuring string defaults
 * (`const { path = "/promotions" } = options`) and template-literal paths
 * (`` `${basePath}/contracts` ``) against those defaults.
 */

/** First line of every generated route file — its presence marks the file as generator-owned. */
export const GENERATED_ROUTE_HEADER = "// GENERATED by voyant admin generate --routes"

/** Is this route-file content generator-owned (vs hand-written/ejected)? */
export function isGeneratedRouteFile(content: string): boolean {
  return content.startsWith(GENERATED_ROUTE_HEADER)
}

/** One route contribution statically extracted from an admin entry source. */
export interface ScannedRouteContribution {
  /** `id:` string literal, or null when not statically resolvable. */
  id: string | null
  /** Resolved route path, or null when not statically resolvable. */
  path: string | null
  /** Raw text of the path value (for skip reporting when unresolvable). */
  rawPath: string | null
  hasComponent: boolean
  /** A lazy `page:` module loader is present (packaged-admin RFC §4.8). */
  hasPage: boolean
  hasLoader: boolean
  hasValidateSearch: boolean
  /** Raw text of the `validateSearch:` value, for schema-identifier resolution. */
  validateSearchRaw: string | null
  /** `ssr:` literal when statically present (`true`/`false`/`"data-only"`). */
  ssr: boolean | "data-only" | null
  /** `preload:` literal when statically present (`false` or a policy string). */
  preload: string | false | null
  /**
   * `destination:` string literal — the semantic destination key this route
   * satisfies (packaged-admin RFC §4.7 endgame) — or null when absent / not
   * statically resolvable.
   */
  destination: string | null
  /**
   * `destinationParams:` object literal mapping route param name →
   * destination param name, or null when absent / not statically resolvable.
   */
  destinationParams: Record<string, string> | null
}

/** Does the contribution carry an implementation (`page` or `component`)? */
export function isImplementedContribution(contribution: ScannedRouteContribution): boolean {
  return contribution.hasPage || contribution.hasComponent
}

/** Runtime-import bindings for generated route files. */
export interface AdminRouteRuntimeImports {
  /** Module exporting the API base-URL getter. */
  apiUrlModule: string
  /** Named export of {@link apiUrlModule} returning the API base URL. */
  apiUrlExport: string
  /** Module exporting the SSR cookie-forwarding fetcher. */
  fetcherModule: string
  /** Named export of {@link fetcherModule}. */
  fetcherExport: string
}

/** Operator-convention defaults for {@link AdminRouteRuntimeImports}. */
export const DEFAULT_ROUTE_RUNTIME_IMPORTS: AdminRouteRuntimeImports = {
  apiUrlModule: "@/lib/env",
  apiUrlExport: "getApiUrl",
  fetcherModule: "@/lib/voyant-fetcher",
  fetcherExport: "operatorFetcher",
}

/** Default host route-tree directory, relative to the config dir. */
export const DEFAULT_ROUTES_DIR = "src/routes/_workspace"

// ---------------------------------------------------------------------------
// Tokenizer-lite: balanced scanning that skips strings, templates, comments.
// ---------------------------------------------------------------------------

/** Index just past a quoted string starting at `start` (a `'` or `"`). */
function skipQuoted(source: string, start: number): number {
  const quote = source[start]
  let i = start + 1
  while (i < source.length) {
    const ch = source[i]
    if (ch === "\\") {
      i += 2
      continue
    }
    if (ch === quote) return i + 1
    i++
  }
  return source.length
}

/** Index just past a template literal starting at `start` (a backtick). */
function skipTemplate(source: string, start: number): number {
  let i = start + 1
  while (i < source.length) {
    const ch = source[i]
    if (ch === "\\") {
      i += 2
      continue
    }
    if (ch === "`") return i + 1
    if (ch === "$" && source[i + 1] === "{") {
      const close = findMatching(source, i + 1)
      i = close === -1 ? source.length : close + 1
      continue
    }
    i++
  }
  return source.length
}

/** Drop leading line/block comments (and surrounding whitespace) from `text`. */
function stripLeadingComments(text: string): string {
  let i = 0
  while (i < text.length) {
    if (/\s/.test(text[i] as string)) {
      i++
      continue
    }
    const skipped = skipComment(text, i)
    if (skipped === i) break
    i = skipped
  }
  return text.slice(i)
}

/** Index just past a comment starting at `start`, or `start` when not a comment. */
function skipComment(source: string, start: number): number {
  if (source[start] !== "/") return start
  const next = source[start + 1]
  if (next === "/") {
    const nl = source.indexOf("\n", start)
    return nl === -1 ? source.length : nl + 1
  }
  if (next === "*") {
    const end = source.indexOf("*/", start + 2)
    return end === -1 ? source.length : end + 2
  }
  return start
}

/**
 * Index of the bracket matching the opener at `openIndex` (`{`, `[`, `(`),
 * or -1. Skips strings, template literals (including their interpolations),
 * and comments.
 */
export function findMatching(source: string, openIndex: number): number {
  const open = source[openIndex]
  const close = open === "{" ? "}" : open === "[" ? "]" : open === "(" ? ")" : null
  if (close === null) return -1
  let depth = 0
  let i = openIndex
  while (i < source.length) {
    const ch = source[i]
    if (ch === '"' || ch === "'") {
      i = skipQuoted(source, i)
      continue
    }
    if (ch === "`") {
      i = skipTemplate(source, i)
      continue
    }
    if (ch === "/") {
      const skipped = skipComment(source, i)
      if (skipped !== i) {
        i = skipped
        continue
      }
    }
    if (ch === open) depth++
    else if (ch === close) {
      depth--
      if (depth === 0) return i
    }
    i++
  }
  return -1
}

/**
 * Split an object-literal body on top-level commas, skipping strings,
 * templates, comments, and anything nested in `()[]{}`.
 */
function splitTopLevel(body: string): string[] {
  const parts: string[] = []
  let depth = 0
  let last = 0
  let i = 0
  while (i < body.length) {
    const ch = body[i]
    if (ch === '"' || ch === "'") {
      i = skipQuoted(body, i)
      continue
    }
    if (ch === "`") {
      i = skipTemplate(body, i)
      continue
    }
    if (ch === "/") {
      const skipped = skipComment(body, i)
      if (skipped !== i) {
        i = skipped
        continue
      }
    }
    if (ch === "(" || ch === "[" || ch === "{") depth++
    else if (ch === ")" || ch === "]" || ch === "}") depth--
    else if (ch === "," && depth === 0) {
      parts.push(body.slice(last, i))
      last = i + 1
    }
    i++
  }
  parts.push(body.slice(last))
  return parts.map((part) => part.trim()).filter((part) => part.length > 0)
}

/**
 * Quoted keys (`"x.y":` / `"x.y"?:`) at brace-depth 0 of an interface or
 * object-literal body. Strings in value position (no following colon) and
 * anything nested are ignored.
 */
function scanTopLevelQuotedKeys(body: string): string[] {
  const keys: string[] = []
  let depth = 0
  let i = 0
  while (i < body.length) {
    const ch = body[i]
    if (ch === '"' || ch === "'") {
      const end = skipQuoted(body, i)
      if (depth === 0) {
        const key = body.slice(i + 1, end - 1)
        let j = end
        while (j < body.length && /\s/.test(body[j] as string)) j++
        if (body[j] === "?") j++
        while (j < body.length && /\s/.test(body[j] as string)) j++
        if (body[j] === ":") keys.push(key)
      }
      i = end
      continue
    }
    if (ch === "`") {
      i = skipTemplate(body, i)
      continue
    }
    if (ch === "/") {
      const skipped = skipComment(body, i)
      if (skipped !== i) {
        i = skipped
        continue
      }
    }
    if (ch === "(" || ch === "[" || ch === "{") depth++
    else if (ch === ")" || ch === "]" || ch === "}") depth--
    i++
  }
  return keys
}

// ---------------------------------------------------------------------------
// Route-contribution scanning
// ---------------------------------------------------------------------------

/**
 * `identifier = "string"` defaults anywhere in the source — in practice the
 * option-destructuring defaults of `create<Domain>AdminExtension`. First
 * occurrence wins.
 */
function collectStringDefaults(source: string): Map<string, string> {
  const defaults = new Map<string, string>()
  const pattern = /([A-Za-z_$][\w$]*)\s*=\s*(["'`])((?:\\.|(?!\2)[^\\])*)\2/g
  let match: RegExpExecArray | null = pattern.exec(source)
  while (match !== null) {
    const name = match[1]
    const value = match[3]
    if (name !== undefined && value !== undefined && !defaults.has(name)) {
      // A template-literal default with interpolations is not a static string.
      if (!(match[2] === "`" && value.includes("${"))) defaults.set(name, value)
    }
    match = pattern.exec(source)
  }
  return defaults
}

function stringLiteralValue(text: string): string | null {
  const match = /^(["'])((?:\\.|(?!\1)[^\\])*)\1$/.exec(text.trim())
  return match?.[2] ?? null
}

/**
 * Parse a `{ key: "value" }` object literal of string-literal values (bare or
 * quoted keys) into a record. Returns null when the text is not such a
 * literal — any non-static entry makes the whole map unresolvable.
 */
function parseStringRecord(text: string): Record<string, string> | null {
  const trimmed = text.trim()
  if (!trimmed.startsWith("{")) return null
  const close = findMatching(trimmed, 0)
  if (close === -1) return null
  const record: Record<string, string> = {}
  for (const rawEntry of splitTopLevel(trimmed.slice(1, close))) {
    const entry = stripLeadingComments(rawEntry)
    const match = /^(?:(["'])((?:\\.|(?!\1)[^\\])*)\1|([A-Za-z_$][\w$]*))\s*:\s*([\s\S]+)$/.exec(
      entry,
    )
    if (!match) return null
    const key = match[3] ?? match[2]
    const value = match[4] === undefined ? null : stringLiteralValue(match[4])
    if (key === undefined || value === null) return null
    record[key] = value
  }
  return record
}

/** Resolve a path value's raw text against the source's string defaults. */
function resolvePathValue(raw: string, defaults: Map<string, string>): string | null {
  const text = raw.trim()
  const literal = stringLiteralValue(text)
  if (literal !== null) return literal
  if (text.startsWith("`") && text.endsWith("`")) {
    const body = text.slice(1, -1)
    let unresolved = false
    const resolved = body.replace(/\$\{\s*([A-Za-z_$][\w$]*)\s*\}/g, (_, name: string) => {
      const value = defaults.get(name)
      if (value === undefined) {
        unresolved = true
        return ""
      }
      return value
    })
    return unresolved || resolved.includes("${") ? null : resolved
  }
  if (/^[A-Za-z_$][\w$]*$/.test(text)) return defaults.get(text) ?? null
  return null
}

/**
 * Index of the `[` opening the first `routes: [...]` array that sits in CODE
 * (not in a comment, string, or template literal), or -1. Doc comments above
 * §4.8 admin entries routinely *mention* `routes: [...]`, so a bare regex
 * over the source would anchor on prose instead of the contribution array.
 */
function findRoutesArrayOpen(source: string): number {
  let i = 0
  while (i < source.length) {
    const ch = source[i]
    if (ch === '"' || ch === "'") {
      i = skipQuoted(source, i)
      continue
    }
    if (ch === "`") {
      i = skipTemplate(source, i)
      continue
    }
    if (ch === "/") {
      const skipped = skipComment(source, i)
      if (skipped !== i) {
        i = skipped
        continue
      }
    }
    if (ch === "r" && !/[\w$]/.test(source[i - 1] ?? " ")) {
      const match = /^routes\s*:\s*\[/.exec(source.slice(i))
      if (match) return i + match[0].length - 1
    }
    i++
  }
  return -1
}

/**
 * Statically extract the route contributions declared in an admin entry
 * source: the objects of the first top-level `routes: [...]` array. Returns
 * an empty array when no routes array is found.
 */
export function scanRouteContributions(source: string): ScannedRouteContribution[] {
  const openBracket = findRoutesArrayOpen(source)
  if (openBracket === -1) return []
  const closeBracket = findMatching(source, openBracket)
  if (closeBracket === -1) return []
  const arrayBody = source.slice(openBracket + 1, closeBracket)
  const defaults = collectStringDefaults(source)

  const contributions: ScannedRouteContribution[] = []
  let i = 0
  while (i < arrayBody.length) {
    const ch = arrayBody[i]
    if (ch === '"' || ch === "'") {
      i = skipQuoted(arrayBody, i)
      continue
    }
    if (ch === "`") {
      i = skipTemplate(arrayBody, i)
      continue
    }
    if (ch === "/") {
      const skipped = skipComment(arrayBody, i)
      if (skipped !== i) {
        i = skipped
        continue
      }
    }
    if (ch === "{") {
      const close = findMatching(arrayBody, i)
      if (close === -1) break
      contributions.push(parseContribution(arrayBody.slice(i + 1, close), defaults))
      i = close + 1
      continue
    }
    i++
  }
  return contributions
}

function parseContribution(
  objectBody: string,
  defaults: Map<string, string>,
): ScannedRouteContribution {
  const contribution: ScannedRouteContribution = {
    id: null,
    path: null,
    rawPath: null,
    hasComponent: false,
    hasPage: false,
    hasLoader: false,
    hasValidateSearch: false,
    validateSearchRaw: null,
    ssr: null,
    preload: null,
    destination: null,
    destinationParams: null,
  }

  for (const rawEntry of splitTopLevel(objectBody)) {
    // Doc comments ride along with the property they precede — drop them so
    // a commented `page:`/`loader:` still key-matches.
    const entry = stripLeadingComments(rawEntry)
    const keyMatch = /^([A-Za-z_$][\w$]*)\s*(:)?/.exec(entry)
    if (!keyMatch) continue
    const key = keyMatch[1]
    const hasColon = keyMatch[2] === ":"
    const value = hasColon ? entry.slice(keyMatch[0].length).trim() : null

    switch (key) {
      case "id":
        contribution.id = value === null ? null : stringLiteralValue(value)
        break
      case "path": {
        // Shorthand `path,` resolves through the destructuring default.
        const raw = value ?? "path"
        contribution.rawPath = raw
        contribution.path = resolvePathValue(raw, defaults)
        break
      }
      case "component":
        contribution.hasComponent = true
        break
      case "page":
        contribution.hasPage = true
        break
      case "loader":
        contribution.hasLoader = true
        break
      case "validateSearch":
        contribution.hasValidateSearch = true
        contribution.validateSearchRaw = value
        break
      case "ssr": {
        if (value === "true") contribution.ssr = true
        else if (value === "false") contribution.ssr = false
        else if (value !== null && stringLiteralValue(value) === "data-only") {
          contribution.ssr = "data-only"
        }
        break
      }
      case "preload": {
        if (value === "false") contribution.preload = false
        else if (value !== null) contribution.preload = stringLiteralValue(value)
        break
      }
      case "destination":
        contribution.destination = value === null ? null : stringLiteralValue(value)
        break
      case "destinationParams":
        contribution.destinationParams = value === null ? null : parseStringRecord(value)
        break
      default:
        break
    }
  }
  return contribution
}

// ---------------------------------------------------------------------------
// Destination scanning (doctor Finding D)
// ---------------------------------------------------------------------------

/**
 * Destination keys an admin entry declares via
 * `declare module "@voyantjs/admin" { interface AdminDestinations { ... } }`.
 */
export function scanDeclaredDestinationKeys(source: string): string[] {
  const keys = new Set<string>()
  const modulePattern = /declare\s+module\s+["']@voyantjs\/admin["']/g
  let moduleMatch: RegExpExecArray | null = modulePattern.exec(source)
  while (moduleMatch !== null) {
    const moduleOpen = source.indexOf("{", moduleMatch.index + moduleMatch[0].length - 1)
    if (moduleOpen !== -1) {
      const moduleClose = findMatching(source, moduleOpen)
      if (moduleClose !== -1) {
        const moduleBody = source.slice(moduleOpen + 1, moduleClose)
        const interfaceMatch = /interface\s+AdminDestinations\b/.exec(moduleBody)
        if (interfaceMatch) {
          const interfaceOpen = moduleBody.indexOf(
            "{",
            interfaceMatch.index + interfaceMatch[0].length,
          )
          if (interfaceOpen !== -1) {
            const interfaceClose = findMatching(moduleBody, interfaceOpen)
            if (interfaceClose !== -1) {
              for (const key of scanTopLevelQuotedKeys(
                moduleBody.slice(interfaceOpen + 1, interfaceClose),
              )) {
                keys.add(key)
              }
            }
          }
        }
      }
    }
    moduleMatch = modulePattern.exec(source)
  }
  return [...keys]
}

/**
 * Keys of the host's destination resolver map — the object literal followed
 * by `satisfies AdminDestinationResolvers`. Returns null when no such map is
 * found in the source (so callers can tell "no map" apart from "empty map").
 */
export function scanResolverMapKeys(source: string): string[] | null {
  const pattern = /=\s*\{/g
  let match: RegExpExecArray | null = pattern.exec(source)
  while (match !== null) {
    const open = match.index + match[0].length - 1
    const close = findMatching(source, open)
    if (close !== -1) {
      const after = source.slice(close + 1)
      if (/^\s*satisfies\s+AdminDestinationResolvers\b/.test(after)) {
        return scanTopLevelQuotedKeys(source.slice(open + 1, close))
      }
    }
    match = pattern.exec(source)
  }
  return null
}

// ---------------------------------------------------------------------------
// Generated destination resolvers (packaged-admin RFC §4.7 endgame)
// ---------------------------------------------------------------------------

/** First line of the generated destinations module — marks it generator-owned. */
export const GENERATED_DESTINATIONS_HEADER = "// GENERATED by voyant admin generate --destinations"

/** Is this destinations-module content generator-owned (vs ejected)? */
export function isGeneratedDestinationsFile(content: string): boolean {
  return content.startsWith(GENERATED_DESTINATIONS_HEADER)
}

/** Default generated destinations module, relative to the config dir. */
export const DEFAULT_GENERATED_DESTINATIONS_MODULE_RELATIVE_PATH =
  "src/admin.destinations.generated.ts"

/** One route-backed destination binding: a contribution's `destination:` annotation. */
export interface ScannedDestinationBinding {
  /** Destination key, e.g. `supplier.detail`. */
  key: string
  /** Resolved route path the resolver interpolates, e.g. `/suppliers/$id`. */
  path: string
  /** Admin entry that contributed the binding (e.g. `@voyantjs/suppliers-react/admin`). */
  importSpec: string
  /** Route param name → destination param name; identity for absent params. */
  params: Record<string, string>
}

export interface CollectDestinationBindingsResult {
  /** Bindings sorted by destination key (deterministic emission order). */
  bindings: ScannedDestinationBinding[]
  /** Human-readable skip notes (unresolvable path, duplicate key). */
  notes: string[]
}

/**
 * Collect the route-backed destination bindings of the mounted admin entries:
 * every route contribution carrying a `destination:` annotation (packaged-admin
 * RFC §4.7 endgame). A contribution whose path is not statically resolvable is
 * skipped with a note; when two contributions claim the same key, the first
 * (in entry order) wins and the duplicate is noted.
 */
export function collectDestinationBindings(
  entries: ReadonlyArray<{ importSpec: string; source: string }>,
): CollectDestinationBindingsResult {
  const byKey = new Map<string, ScannedDestinationBinding>()
  const notes: string[] = []
  for (const entry of entries) {
    for (const contribution of scanRouteContributions(entry.source)) {
      if (contribution.destination === null) continue
      if (contribution.path === null) {
        notes.push(
          `skipped destination "${contribution.destination}" (${entry.importSpec}) — ` +
            `its route path is not statically resolvable`,
        )
        continue
      }
      const existing = byKey.get(contribution.destination)
      if (existing) {
        notes.push(
          `skipped duplicate destination "${contribution.destination}" (${entry.importSpec} ` +
            `${contribution.path}) — already bound by ${existing.importSpec} ${existing.path}`,
        )
        continue
      }
      byKey.set(contribution.destination, {
        key: contribution.destination,
        path: contribution.path,
        importSpec: entry.importSpec,
        params: contribution.destinationParams ?? {},
      })
    }
  }
  return {
    bindings: [...byKey.values()].sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0)),
    notes,
  }
}

/** The `satisfies Partial<AdminDestinationResolvers>` marker of the generated map. */
const GENERATED_DESTINATIONS_SATISFIES =
  /^\s*satisfies\s+Partial\s*<\s*AdminDestinationResolvers\s*>/

/**
 * Keys of a generated destinations module — the object literal followed by
 * `satisfies Partial<AdminDestinationResolvers>`. Returns null when no such
 * map is found (so callers can tell "no map" apart from "empty map").
 */
export function scanGeneratedDestinationKeys(source: string): string[] | null {
  const pattern = /=\s*\{/g
  let match: RegExpExecArray | null = pattern.exec(source)
  while (match !== null) {
    const open = match.index + match[0].length - 1
    const close = findMatching(source, open)
    if (close !== -1 && GENERATED_DESTINATIONS_SATISFIES.test(source.slice(close + 1))) {
      return scanTopLevelQuotedKeys(source.slice(open + 1, close))
    }
    match = pattern.exec(source)
  }
  return null
}

/** Render one binding's resolver: pure path interpolation of the route path. */
function renderDestinationResolver(binding: ScannedDestinationBinding): string[] {
  const destParams: string[] = []
  const expression = binding.path
    .split("/")
    .map((segment) => {
      if (!segment.startsWith("$") || segment.length === 1) return segment
      const routeParam = segment.slice(1)
      const destParam = binding.params[routeParam] ?? routeParam
      if (!destParams.includes(destParam)) destParams.push(destParam)
      return `\${encodeURIComponent(${destParam})}`
    })
    .join("/")
  const body = destParams.length === 0 ? `"${expression}"` : `\`${expression}\``
  const head = destParams.length === 0 ? "()" : `({ ${destParams.join(", ")} })`
  const single = `  "${binding.key}": ${head} => ${body},`
  if (single.length <= MAX_LINE_WIDTH) return [single]
  return [`  "${binding.key}": ${head} =>`, `    ${body},`]
}

export interface RenderAdminDestinationsModuleOptions {
  /** Bindings pre-sorted by key (see {@link collectDestinationBindings}). */
  bindings: ReadonlyArray<ScannedDestinationBinding>
  /**
   * Admin-entry import specifiers to bind TYPE-ONLY, so every declared
   * `AdminDestinations` augmentation (including keys a binding's owning
   * entry consumes from a sibling package) is in scope. Sorted for
   * deterministic output.
   */
  importSpecs: ReadonlyArray<string>
}

/**
 * Render the generated destinations module (packaged-admin RFC §4.7 endgame):
 * one pure path-interpolation resolver per route-backed destination binding,
 * `satisfies Partial<AdminDestinationResolvers>` so each resolver typechecks
 * against the declared key shape. Hosts spread the exported map under their
 * hand-written custom resolvers:
 *
 * ```ts
 * { ...generatedAdminDestinations, "custom.key": ... } satisfies AdminDestinationResolvers
 * ```
 *
 * Deterministic output — `--check` stays a pure string comparison.
 */
export function renderAdminDestinationsModule(
  options: RenderAdminDestinationsModuleOptions,
): string {
  const { bindings, importSpecs } = options
  const lines: string[] = [
    `${GENERATED_DESTINATIONS_HEADER} — do not edit.`,
    "// Generated destination resolvers (packaged-admin RFC §4.7 endgame): every",
    "// route contribution that declares a `destination:` annotation becomes a",
    "// pure path-interpolation resolver here. The host's resolver map spreads",
    "// this object FIRST and hand-writes only the genuinely custom resolvers",
    "// (search-param construction, multi-route targets):",
    "//   { ...generatedAdminDestinations, ...custom } satisfies AdminDestinationResolvers",
    "// To eject the whole map, delete this header — the generator skips files",
    "// without it. To override one key, re-declare it after the spread in the",
    "// host map (later properties win); to unbind one, remove the",
    "// contribution's `destination:` annotation and regenerate.",
    `import type { AdminDestinationResolvers } from "@voyantjs/admin"`,
    "// Type-only: bind the mounted admin entries' `AdminDestinations`",
    "// augmentations into this module without pulling any runtime code into",
    "// the chunk that imports the resolver map.",
    ...[...new Set(importSpecs)].sort().map((spec) => `import type {} from "${spec}"`),
    "",
    "/** Resolvers for the route-backed subset of the declared destination keys. */",
    "export const generatedAdminDestinations = {",
    ...bindings.flatMap(renderDestinationResolver),
    "} satisfies Partial<AdminDestinationResolvers>",
  ]
  return `${lines.join("\n")}\n`
}

// ---------------------------------------------------------------------------
// Extension-id + search-schema scanning (code-assembled module, RFC §4.8)
// ---------------------------------------------------------------------------

/**
 * The `id:` string literal of the first `defineAdminExtension({ ... })`
 * object in an admin entry source, or null when not statically resolvable.
 * The generated module resolves extensions from the host registry by this id.
 */
export function scanExtensionId(source: string): string | null {
  const callMatch = /\bdefineAdminExtension\s*\(/.exec(source)
  if (!callMatch) return null
  const open = source.indexOf("{", callMatch.index + callMatch[0].length - 1)
  if (open === -1) return null
  const close = findMatching(source, open)
  if (close === -1) return null
  for (const entry of splitTopLevel(source.slice(open + 1, close))) {
    const match = /^id\s*:\s*([\s\S]+)$/.exec(entry)
    if (match?.[1] !== undefined) return stringLiteralValue(match[1])
  }
  return null
}

/** Is `ident` a named export of the entry source (direct or brace re-export)? */
export function isExportedIdent(source: string, ident: string): boolean {
  if (new RegExp(`\\bexport\\s+(?:const|let|var|function|class)\\s+${ident}\\b`).test(source)) {
    return true
  }
  const bracePattern = /\bexport\s*(?:type\s*)?\{([^}]*)\}/g
  let match: RegExpExecArray | null = bracePattern.exec(source)
  while (match !== null) {
    const body = match[1] ?? ""
    for (const part of body.split(",")) {
      const entry = part.trim()
      if (entry.length === 0 || entry.startsWith("type ")) continue
      const asMatch = /\bas\s+([A-Za-z_$][\w$]*)$/.exec(entry)
      const exported = asMatch?.[1] ?? entry
      if (exported === ident) return true
    }
    match = bracePattern.exec(source)
  }
  return false
}

function extractParseIdent(text: string): string | null {
  return /([A-Za-z_$][\w$]*)\.parse\s*\(/.exec(text)?.[1] ?? null
}

/**
 * Resolve a contribution's `validateSearch:` raw value to the EXPORTED search
 * schema identifier the generated module imports for typed links — the
 * `validateSearch: bookingsIndexSearchSchema` literal in the emitted
 * `createRoute` options. Handles the shapes §4.8 admin entries write:
 *
 * - `validateSearch: (search) => someSchema.parse(search)` → `someSchema`
 * - `validateSearch: someSchema` (exported directly) → `someSchema`
 * - `validateSearch: localHelper` where the entry defines
 *   `const localHelper = (search) => someSchema.parse(search)` → `someSchema`
 *
 * Returns null when no identifier resolves or the schema is not exported
 * from the entry (the module cannot import it).
 */
export function resolveSearchSchemaIdent(raw: string, source: string): string | null {
  const text = raw.trim()
  let ident = extractParseIdent(text)
  if (ident === null && /^[A-Za-z_$][\w$]*$/.test(text)) {
    if (isExportedIdent(source, text)) {
      ident = text
    } else {
      // Follow one local alias: `const helper = (s) => schema.parse(s)`.
      const defMatch = new RegExp(`(?:const|let|var)\\s+${text}\\s*(?::[^=\\n]*)?=`).exec(source)
      if (defMatch) {
        const defStart = defMatch.index + defMatch[0].length
        ident = extractParseIdent(source.slice(defStart, defStart + 400))
      }
    }
  }
  return ident !== null && isExportedIdent(source, ident) ? ident : null
}

// ---------------------------------------------------------------------------
// Generated-module scanning (doctor Finding C)
// ---------------------------------------------------------------------------

/** Default code-assembled admin route module, relative to the config dir. */
export const DEFAULT_GENERATED_ROUTES_MODULE_RELATIVE_PATH = "src/admin.routes.generated.tsx"

/**
 * The route-path literals of a code-assembled admin route module — the
 * `path: "..."` options of its `createRoute` calls. Static text scan; in the
 * generated module every `path:` literal is a route path, so a contribution
 * path appearing here is bound without any route file existing for it.
 */
export function scanGeneratedModuleRoutePaths(source: string): string[] {
  const paths = new Set<string>()
  const pattern = /\bpath\s*:\s*["']([^"']+)["']/g
  let match: RegExpExecArray | null = pattern.exec(source)
  while (match !== null) {
    if (match[1] !== undefined) paths.add(match[1])
    match = pattern.exec(source)
  }
  return [...paths]
}

// ---------------------------------------------------------------------------
// Manifest `admin.routes` config
// ---------------------------------------------------------------------------

/** Import bindings of the code-assembled module (runtime + host registry). */
export interface AdminRoutesModuleImports extends AdminRouteRuntimeImports {
  /** Module exporting the host's admin extension registry. */
  registryModule: string
  /** Named export of {@link registryModule} (the registered extensions array). */
  registryExport: string
}

/** Operator-convention defaults for {@link AdminRoutesModuleImports}. */
export const DEFAULT_ROUTES_MODULE_IMPORTS: AdminRoutesModuleImports = {
  ...DEFAULT_ROUTE_RUNTIME_IMPORTS,
  registryModule: "@/lib/admin-extensions",
  registryExport: "adminExtensions",
}

/** The manifest's `admin.routes` block, resolved against operator defaults. */
export interface AdminRoutesManifestConfig {
  /** Host route-tree directory (relative to the config dir), when configured. */
  dir?: string
  /** Code-assembled module path (relative to the config dir), when configured. */
  out?: string
  /** Workspace layout route module, when configured (else derived from `dir`). */
  workspaceRouteModule?: string
  imports: AdminRoutesModuleImports
}

/**
 * Read the manifest's `admin.routes` block structurally (older core types
 * lack it) and fill the operator-convention defaults for import bindings.
 */
export function resolveAdminRoutesManifestConfig(config: unknown): AdminRoutesManifestConfig {
  const routes = (
    config as {
      admin?: {
        routes?: {
          dir?: string
          out?: string
          workspaceRouteModule?: string
          apiUrlModule?: string
          apiUrlExport?: string
          fetcherModule?: string
          fetcherExport?: string
          registryModule?: string
          registryExport?: string
        }
      }
    }
  ).admin?.routes
  const str = (value: unknown): string | undefined =>
    typeof value === "string" && value.length > 0 ? value : undefined
  return {
    dir: str(routes?.dir),
    out: str(routes?.out),
    workspaceRouteModule: str(routes?.workspaceRouteModule),
    imports: {
      apiUrlModule: str(routes?.apiUrlModule) ?? DEFAULT_ROUTES_MODULE_IMPORTS.apiUrlModule,
      apiUrlExport: str(routes?.apiUrlExport) ?? DEFAULT_ROUTES_MODULE_IMPORTS.apiUrlExport,
      fetcherModule: str(routes?.fetcherModule) ?? DEFAULT_ROUTES_MODULE_IMPORTS.fetcherModule,
      fetcherExport: str(routes?.fetcherExport) ?? DEFAULT_ROUTES_MODULE_IMPORTS.fetcherExport,
      registryModule: str(routes?.registryModule) ?? DEFAULT_ROUTES_MODULE_IMPORTS.registryModule,
      registryExport: str(routes?.registryExport) ?? DEFAULT_ROUTES_MODULE_IMPORTS.registryExport,
    },
  }
}

// ---------------------------------------------------------------------------
// Route-file paths + rendering
// ---------------------------------------------------------------------------

/**
 * The createFileRoute id for a contribution path hosted under `routesDir`
 * (relative to the config dir, e.g. "src/routes/_workspace"): the dir's
 * segments after `routes` become the tree prefix, and index files keep the
 * trailing slash (`/_workspace/promotions/`).
 */
export function fileRouteIdFor(routesDirRel: string, routePath: string): string {
  const segments = routesDirRel.split(/[\\/]/).filter(Boolean)
  const routesIndex = segments.lastIndexOf("routes")
  const prefixSegments = routesIndex === -1 ? [] : segments.slice(routesIndex + 1)
  const prefix = prefixSegments.length > 0 ? `/${prefixSegments.join("/")}` : ""
  return `${prefix}${routePath}/`
}

/** Canonical generated-file location for a contribution path: `<rel>/index.tsx`. */
export function canonicalRouteFileRelPath(routePath: string): string {
  return join(...routePath.replace(/^\//, "").split("/"), "index.tsx")
}

/**
 * Alternative file-routing spellings a hand-written host for `routePath`
 * may already use. Any existing one means the route is already bound and the
 * generator must not create a parallel file.
 */
export function alternativeRouteFileRelPaths(routePath: string): string[] {
  const rel = routePath.replace(/^\//, "")
  const dotted = rel.replaceAll("/", ".")
  const segments = rel.split("/")
  return [
    `${join(...segments)}.tsx`,
    `${join(...segments)}.ts`,
    join(...segments, "index.ts"),
    join(...segments, "route.tsx"),
    `${dotted}.tsx`,
    `${dotted}.index.tsx`,
  ]
}

export interface RenderRouteFileOptions {
  /** createFileRoute id, e.g. `/_workspace/promotions/`. */
  fileRouteId: string
  /** Admin entry import specifier, e.g. `@voyantjs/promotions-react/admin`. */
  importSpec: string
  /** Extension factory export, e.g. `createPromotionsAdminExtension`. */
  exportName: string
  /** Route contribution id, e.g. `promotions-index`. */
  routeId: string
  ssr: boolean | "data-only" | null
  preload: string | false | null
  hasLoader: boolean
  hasValidateSearch: boolean
  runtime: AdminRouteRuntimeImports
}

/**
 * Render a generated thin route file: resolve the contribution through
 * `requireAdminRoute` and bind it to the host's file-based route tree with
 * the app runtime — exactly what the hand-written thin hosts do. Output is
 * deterministic so `--check` stays a pure string comparison.
 */
export function renderRouteFile(options: RenderRouteFileOptions): string {
  const { fileRouteId, importSpec, exportName, routeId, ssr, preload, runtime } = options

  const imports = [
    `import { createFileRoute } from "@tanstack/react-router"`,
    `import { requireAdminRoute } from "@voyantjs/admin"`,
    `import { ${exportName} } from "${importSpec}"`,
  ]
  if (options.hasLoader) {
    imports.push(
      `import { ${runtime.apiUrlExport} } from "${runtime.apiUrlModule}"`,
      `import { ${runtime.fetcherExport} } from "${runtime.fetcherModule}"`,
    )
  }

  const routeOptions: string[] = []
  if (ssr !== null) {
    routeOptions.push(`  ssr: ${typeof ssr === "string" ? JSON.stringify(ssr) : String(ssr)},`)
  }
  if (preload !== null) {
    routeOptions.push(`  preload: ${preload === false ? "false" : JSON.stringify(preload)},`)
  }
  if (options.hasValidateSearch) {
    routeOptions.push(`  validateSearch: route.validateSearch,`)
  }
  if (options.hasLoader) {
    routeOptions.push(
      `  loader: ({ context }) =>`,
      `    route.loader?.({`,
      `      queryClient: context.queryClient,`,
      `      runtime: { baseUrl: ${runtime.apiUrlExport}(), fetcher: ${runtime.fetcherExport} },`,
      `    }),`,
    )
  }
  routeOptions.push(`  component: RouteComponent,`)

  return [
    `${GENERATED_ROUTE_HEADER} — do not edit.`,
    `// Thin host for the package-delivered ${importSpec} route "${routeId}"`,
    `// (packaged-admin RFC §4.2): page, loader, and SSR mode are package-owned;`,
    `// this file only binds them into the host's file-based route tree with the`,
    `// app runtime. Recreate with \`voyant admin generate --routes\`.`,
    `// To eject and hand-maintain this host, delete this header — the generator`,
    `// skips files without it.`,
    ...imports,
    ``,
    `const route = requireAdminRoute(${exportName}(), "${routeId}")`,
    `// Top-level identifier on purpose: the router's code-splitter can extract`,
    `// an identifier binding, but not a member expression.`,
    `const RouteComponent = route.component`,
    ``,
    `export const Route = createFileRoute("${fileRouteId}")({`,
    ...routeOptions,
    `})`,
    ``,
  ].join("\n")
}

// ---------------------------------------------------------------------------
// Code-assembled module rendering (packaged-admin RFC §4.8)
// ---------------------------------------------------------------------------

const MAX_LINE_WIDTH = 100
const SECTION_RULE = `// ${"-".repeat(75)}`

/**
 * The route-id prefix the host's routes dir contributes to TanStack route
 * ids: the dir's segments after `routes` (e.g. `src/routes/_workspace` →
 * `/_workspace`). The generated module's `AdminExtensionRoutesById` keys are
 * this prefix plus the route path.
 */
export function routeIdPrefixFor(routesDirRel: string): string {
  const segments = routesDirRel.split(/[\\/]/).filter(Boolean)
  const routesIndex = segments.lastIndexOf("routes")
  const prefixSegments = routesIndex === -1 ? [] : segments.slice(routesIndex + 1)
  return prefixSegments.length > 0 ? `/${prefixSegments.join("/")}` : ""
}

/**
 * Derive the workspace layout route module from the routes dir, following
 * the operator's `@/` → `src/` alias convention: `src/routes/_workspace` →
 * `@/routes/_workspace/route`. Override via `admin.routes.workspaceRouteModule`
 * when the host aliases differently.
 */
export function workspaceRouteModuleFor(routesDirRel: string): string {
  const normalized = routesDirRel.replace(/[\\/]+$/, "").replaceAll("\\", "/")
  const aliased = normalized.startsWith("src/") ? normalized.slice("src/".length) : normalized
  return `@/${aliased}/route`
}

/** One `createRoute` entry of the code-assembled module. */
export interface AdminRoutesModuleRoute {
  /** Exported route const, e.g. `PromotionsIndexRoute`. */
  constName: string
  /** Contribution id resolved through the registry, e.g. `promotions-index`. */
  routeId: string
  /** Literal route path under the workspace layout, e.g. `/promotions`. */
  path: string
  /** Exported search-schema identifier for `validateSearch:`, when resolved. */
  searchSchemaIdent: string | null
}

/** One extension's block of the code-assembled module. */
export interface AdminRoutesModuleSection {
  /** Registry id resolved via `extension("<id>")`. */
  extensionId: string
  /** Admin entry import specifier — the source of any search-schema imports. */
  importSpec: string
  routes: ReadonlyArray<AdminRoutesModuleRoute>
}

export interface RenderAdminRoutesModuleOptions {
  /** Output file base name (for the error-message tag), e.g. `admin.routes.generated`. */
  moduleBaseName: string
  /** Extension sections, pre-sorted by extension id. */
  sections: ReadonlyArray<AdminRoutesModuleSection>
  imports: AdminRoutesModuleImports
  /** Workspace layout route module, e.g. `@/routes/_workspace/route`. */
  workspaceRouteModule: string
  /** Route-id prefix of the workspace layout, e.g. `/_workspace`. */
  routeIdPrefix: string
}

/** `@/lib/admin-extensions` → `src/lib/admin-extensions.tsx` (header prose). */
function registryDisplayPath(registryModule: string): string {
  return registryModule.startsWith("@/") ? `src/${registryModule.slice(2)}.tsx` : registryModule
}

/** Named-import line(s), wrapped beyond the formatter's line width. */
function formatNamedImport(names: ReadonlyArray<string>, spec: string): string[] {
  const single = `import { ${names.join(", ")} } from "${spec}"`
  if (single.length <= MAX_LINE_WIDTH) return [single]
  return ["import {", ...names.map((name) => `  ${name},`), `} from "${spec}"`]
}

/** The `...adminExtensionRouteOptions(...)` spread, wrapped beyond line width. */
function formatRouteOptionsSpread(extensionConst: string, routeId: string): string[] {
  const single = `  ...adminExtensionRouteOptions(${extensionConst}, "${routeId}", runtime),`
  if (single.length <= MAX_LINE_WIDTH) return [single]
  return [
    "  ...adminExtensionRouteOptions(",
    `    ${extensionConst},`,
    `    "${routeId}",`,
    "    runtime,",
    "  ),",
  ]
}

/**
 * Render the code-assembled admin route module (packaged-admin RFC §4.8):
 * one `createRoute` per extension route contribution, options resolved from
 * the host-registered extension instances via `adminExtensionRouteOptions`,
 * plus the three typed-link map interfaces the host's `router.tsx` merges
 * into its file-route types. Deterministic output — `--check` stays a pure
 * string comparison.
 */
export function renderAdminRoutesModule(options: RenderAdminRoutesModuleOptions): string {
  const { moduleBaseName, sections, imports, workspaceRouteModule, routeIdPrefix } = options

  // Search-schema imports grouped by admin entry, both levels sorted.
  const schemaImportsBySpec = new Map<string, Set<string>>()
  for (const section of sections) {
    for (const route of section.routes) {
      if (route.searchSchemaIdent === null) continue
      const idents = schemaImportsBySpec.get(section.importSpec) ?? new Set<string>()
      idents.add(route.searchSchemaIdent)
      schemaImportsBySpec.set(section.importSpec, idents)
    }
  }
  const schemaImportLines = [...schemaImportsBySpec.keys()]
    .sort()
    .flatMap((spec) =>
      formatNamedImport([...(schemaImportsBySpec.get(spec) as Set<string>)].sort(), spec),
    )

  const appImports: Array<{ spec: string; names: string[] }> = [
    { spec: imports.registryModule, names: [imports.registryExport] },
    { spec: imports.apiUrlModule, names: [imports.apiUrlExport] },
    { spec: imports.fetcherModule, names: [imports.fetcherExport] },
    { spec: workspaceRouteModule, names: ["Route as WorkspaceRoute"] },
  ]
  const appImportLines = appImports
    .sort((a, b) => (a.spec < b.spec ? -1 : a.spec > b.spec ? 1 : 0))
    .flatMap((entry) => formatNamedImport(entry.names, entry.spec))

  const lines: string[] = [
    `${GENERATED_ROUTE_HEADER} — do not edit.`,
    "// Code-assembled admin route tree for package-delivered pages (packaged-admin",
    "// RFC §4.8 endgame): every extension route contribution becomes a code-based",
    "// route grafted under the workspace layout — NO per-route files exist for",
    "// package-delivered pages. Path literals + typed search contracts stay in",
    "// this module (they are what gives the host typed links via the",
    "// `AdminExtensionRoutesBy*` interfaces merged in `router.tsx`); pages,",
    "// loaders, SSR modes, and boundaries come from the extension contributions",
    `// (resolved from the host-owned registry in \`${registryDisplayPath(imports.registryModule)}\`,`,
    "// so app-supplied factory options apply to the assembled routes).",
    "// To eject a route, remove it here (and from the maps below) and add a",
    "// hand-written route file — the generator skips files without this header.",
    `import { createRoute } from "@tanstack/react-router"`,
    `import { adminExtensionRouteOptions } from "@voyantjs/admin-app"`,
    ...schemaImportLines,
    "",
    ...appImportLines,
    "",
    `// ${imports.fetcherExport} so SSR loaders forward the request cookie; resolved per`,
    `// loader call because \`${imports.apiUrlExport}()\` reads the runtime origin.`,
    `const runtime = () => ({ baseUrl: ${imports.apiUrlExport}(), fetcher: ${imports.fetcherExport} })`,
    "",
    "const workspace = () => WorkspaceRoute",
    "",
    "function extension(id: string) {",
    `  const match = ${imports.registryExport}.find((candidate) => candidate.id === id)`,
    "  if (!match) {",
    // The emitted line nests a template literal — hence the escapes.
    `    throw new Error(\`[${moduleBaseName}] No registered admin extension "\${id}".\`)`,
    "  }",
    "  return match",
    "}",
  ]

  for (const section of sections) {
    const extensionConst = `${toCamelIdent(section.extensionId)}Extension`
    lines.push(
      "",
      SECTION_RULE,
      `// ${section.extensionId}`,
      SECTION_RULE,
      "",
      `const ${extensionConst} = extension("${section.extensionId}")`,
    )
    for (const route of section.routes) {
      lines.push(
        "",
        `export const ${route.constName} = createRoute({`,
        "  getParentRoute: workspace,",
        `  path: "${route.path}",`,
      )
      if (route.searchSchemaIdent !== null) {
        lines.push(`  validateSearch: ${route.searchSchemaIdent},`)
      }
      lines.push(...formatRouteOptionsSpread(extensionConst, route.routeId), "})")
    }
  }

  const allRoutes = sections.flatMap((section) => section.routes)
  lines.push(
    "",
    SECTION_RULE,
    "// tree + typed-link maps",
    SECTION_RULE,
    "",
    "export const adminExtensionRoutes = [",
    ...allRoutes.map((route) => `  ${route.constName},`),
    "]",
  )
  for (const [interfaceName, keyFor] of [
    ["AdminExtensionRoutesByFullPath", (route: AdminRoutesModuleRoute) => route.path],
    ["AdminExtensionRoutesByTo", (route: AdminRoutesModuleRoute) => route.path],
    [
      "AdminExtensionRoutesById",
      (route: AdminRoutesModuleRoute) => `${routeIdPrefix}${route.path}`,
    ],
  ] as const) {
    lines.push(
      "",
      `export interface ${interfaceName} {`,
      ...allRoutes.map((route) => `  "${keyFor(route)}": typeof ${route.constName}`),
      "}",
    )
  }

  return `${lines.join("\n")}\n`
}

/** Camel-case an extension id for its module-local const (`crm` → `crm`). */
function toCamelIdent(id: string): string {
  const parts = id.split(/[^A-Za-z0-9]+/).filter(Boolean)
  if (parts.length === 0) return "ext"
  return (
    (parts[0] as string).charAt(0).toLowerCase() +
    (parts[0] as string).slice(1) +
    parts
      .slice(1)
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join("")
  )
}
