import { join } from "node:path"

/**
 * Static analysis + rendering for `voyant admin generate --routes` and the
 * admin doctor's destination-parity finding (packaged-admin RFC §4.2 / §4.7).
 *
 * Everything here is pure source-text scanning — no admin entry is ever
 * imported or executed. The scanners are deliberately convention-bound: they
 * understand the `defineAdminExtension({ routes: [...] })` shape and the
 * `declare module "@voyantjs/admin"` destination declarations the `*-ui`
 * packages actually write, resolving option-destructuring string defaults
 * (`const { path = "/promotions" } = options`) and template-literal paths
 * (`` `${basePath}/contracts` ``) against those defaults.
 */

/** First line of every generated route file — its presence marks the file as generator-owned. */
export const GENERATED_ROUTE_HEADER = "// GENERATED by voyant admin generate --routes"

/** Is this route-file content generator-owned (vs hand-written/ejected)? */
export function isGeneratedRouteFile(content: string): boolean {
  return content.startsWith(GENERATED_ROUTE_HEADER)
}

/** One route contribution statically extracted from an admin entry source. */
export interface ScannedRouteContribution {
  /** `id:` string literal, or null when not statically resolvable. */
  id: string | null
  /** Resolved route path, or null when not statically resolvable. */
  path: string | null
  /** Raw text of the path value (for skip reporting when unresolvable). */
  rawPath: string | null
  hasComponent: boolean
  hasLoader: boolean
  hasValidateSearch: boolean
  /** `ssr:` literal when statically present (`true`/`false`/`"data-only"`). */
  ssr: boolean | "data-only" | null
  /** `preload:` literal when statically present (`false` or a policy string). */
  preload: string | false | null
}

/** Runtime-import bindings for generated route files. */
export interface AdminRouteRuntimeImports {
  /** Module exporting the API base-URL getter. */
  apiUrlModule: string
  /** Named export of {@link apiUrlModule} returning the API base URL. */
  apiUrlExport: string
  /** Module exporting the SSR cookie-forwarding fetcher. */
  fetcherModule: string
  /** Named export of {@link fetcherModule}. */
  fetcherExport: string
}

/** Operator-convention defaults for {@link AdminRouteRuntimeImports}. */
export const DEFAULT_ROUTE_RUNTIME_IMPORTS: AdminRouteRuntimeImports = {
  apiUrlModule: "@/lib/env",
  apiUrlExport: "getApiUrl",
  fetcherModule: "@/lib/voyant-fetcher",
  fetcherExport: "operatorFetcher",
}

/** Default host route-tree directory, relative to the config dir. */
export const DEFAULT_ROUTES_DIR = "src/routes/_workspace"

// ---------------------------------------------------------------------------
// Tokenizer-lite: balanced scanning that skips strings, templates, comments.
// ---------------------------------------------------------------------------

/** Index just past a quoted string starting at `start` (a `'` or `"`). */
function skipQuoted(source: string, start: number): number {
  const quote = source[start]
  let i = start + 1
  while (i < source.length) {
    const ch = source[i]
    if (ch === "\\") {
      i += 2
      continue
    }
    if (ch === quote) return i + 1
    i++
  }
  return source.length
}

/** Index just past a template literal starting at `start` (a backtick). */
function skipTemplate(source: string, start: number): number {
  let i = start + 1
  while (i < source.length) {
    const ch = source[i]
    if (ch === "\\") {
      i += 2
      continue
    }
    if (ch === "`") return i + 1
    if (ch === "$" && source[i + 1] === "{") {
      const close = findMatching(source, i + 1)
      i = close === -1 ? source.length : close + 1
      continue
    }
    i++
  }
  return source.length
}

/** Index just past a comment starting at `start`, or `start` when not a comment. */
function skipComment(source: string, start: number): number {
  if (source[start] !== "/") return start
  const next = source[start + 1]
  if (next === "/") {
    const nl = source.indexOf("\n", start)
    return nl === -1 ? source.length : nl + 1
  }
  if (next === "*") {
    const end = source.indexOf("*/", start + 2)
    return end === -1 ? source.length : end + 2
  }
  return start
}

/**
 * Index of the bracket matching the opener at `openIndex` (`{`, `[`, `(`),
 * or -1. Skips strings, template literals (including their interpolations),
 * and comments.
 */
export function findMatching(source: string, openIndex: number): number {
  const open = source[openIndex]
  const close = open === "{" ? "}" : open === "[" ? "]" : open === "(" ? ")" : null
  if (close === null) return -1
  let depth = 0
  let i = openIndex
  while (i < source.length) {
    const ch = source[i]
    if (ch === '"' || ch === "'") {
      i = skipQuoted(source, i)
      continue
    }
    if (ch === "`") {
      i = skipTemplate(source, i)
      continue
    }
    if (ch === "/") {
      const skipped = skipComment(source, i)
      if (skipped !== i) {
        i = skipped
        continue
      }
    }
    if (ch === open) depth++
    else if (ch === close) {
      depth--
      if (depth === 0) return i
    }
    i++
  }
  return -1
}

/**
 * Split an object-literal body on top-level commas, skipping strings,
 * templates, comments, and anything nested in `()[]{}`.
 */
function splitTopLevel(body: string): string[] {
  const parts: string[] = []
  let depth = 0
  let last = 0
  let i = 0
  while (i < body.length) {
    const ch = body[i]
    if (ch === '"' || ch === "'") {
      i = skipQuoted(body, i)
      continue
    }
    if (ch === "`") {
      i = skipTemplate(body, i)
      continue
    }
    if (ch === "/") {
      const skipped = skipComment(body, i)
      if (skipped !== i) {
        i = skipped
        continue
      }
    }
    if (ch === "(" || ch === "[" || ch === "{") depth++
    else if (ch === ")" || ch === "]" || ch === "}") depth--
    else if (ch === "," && depth === 0) {
      parts.push(body.slice(last, i))
      last = i + 1
    }
    i++
  }
  parts.push(body.slice(last))
  return parts.map((part) => part.trim()).filter((part) => part.length > 0)
}

/**
 * Quoted keys (`"x.y":` / `"x.y"?:`) at brace-depth 0 of an interface or
 * object-literal body. Strings in value position (no following colon) and
 * anything nested are ignored.
 */
function scanTopLevelQuotedKeys(body: string): string[] {
  const keys: string[] = []
  let depth = 0
  let i = 0
  while (i < body.length) {
    const ch = body[i]
    if (ch === '"' || ch === "'") {
      const end = skipQuoted(body, i)
      if (depth === 0) {
        const key = body.slice(i + 1, end - 1)
        let j = end
        while (j < body.length && /\s/.test(body[j] as string)) j++
        if (body[j] === "?") j++
        while (j < body.length && /\s/.test(body[j] as string)) j++
        if (body[j] === ":") keys.push(key)
      }
      i = end
      continue
    }
    if (ch === "`") {
      i = skipTemplate(body, i)
      continue
    }
    if (ch === "/") {
      const skipped = skipComment(body, i)
      if (skipped !== i) {
        i = skipped
        continue
      }
    }
    if (ch === "(" || ch === "[" || ch === "{") depth++
    else if (ch === ")" || ch === "]" || ch === "}") depth--
    i++
  }
  return keys
}

// ---------------------------------------------------------------------------
// Route-contribution scanning
// ---------------------------------------------------------------------------

/**
 * `identifier = "string"` defaults anywhere in the source — in practice the
 * option-destructuring defaults of `create<Domain>AdminExtension`. First
 * occurrence wins.
 */
function collectStringDefaults(source: string): Map<string, string> {
  const defaults = new Map<string, string>()
  const pattern = /([A-Za-z_$][\w$]*)\s*=\s*(["'`])((?:\\.|(?!\2)[^\\])*)\2/g
  let match: RegExpExecArray | null = pattern.exec(source)
  while (match !== null) {
    const name = match[1]
    const value = match[3]
    if (name !== undefined && value !== undefined && !defaults.has(name)) {
      // A template-literal default with interpolations is not a static string.
      if (!(match[2] === "`" && value.includes("${"))) defaults.set(name, value)
    }
    match = pattern.exec(source)
  }
  return defaults
}

function stringLiteralValue(text: string): string | null {
  const match = /^(["'])((?:\\.|(?!\1)[^\\])*)\1$/.exec(text.trim())
  return match?.[2] ?? null
}

/** Resolve a path value's raw text against the source's string defaults. */
function resolvePathValue(raw: string, defaults: Map<string, string>): string | null {
  const text = raw.trim()
  const literal = stringLiteralValue(text)
  if (literal !== null) return literal
  if (text.startsWith("`") && text.endsWith("`")) {
    const body = text.slice(1, -1)
    let unresolved = false
    const resolved = body.replace(/\$\{\s*([A-Za-z_$][\w$]*)\s*\}/g, (_, name: string) => {
      const value = defaults.get(name)
      if (value === undefined) {
        unresolved = true
        return ""
      }
      return value
    })
    return unresolved || resolved.includes("${") ? null : resolved
  }
  if (/^[A-Za-z_$][\w$]*$/.test(text)) return defaults.get(text) ?? null
  return null
}

/**
 * Statically extract the route contributions declared in an admin entry
 * source: the objects of the first top-level `routes: [...]` array. Returns
 * an empty array when no routes array is found.
 */
export function scanRouteContributions(source: string): ScannedRouteContribution[] {
  const arrayMatch = /\broutes\s*:\s*\[/.exec(source)
  if (!arrayMatch) return []
  const openBracket = arrayMatch.index + arrayMatch[0].length - 1
  const closeBracket = findMatching(source, openBracket)
  if (closeBracket === -1) return []
  const arrayBody = source.slice(openBracket + 1, closeBracket)
  const defaults = collectStringDefaults(source)

  const contributions: ScannedRouteContribution[] = []
  let i = 0
  while (i < arrayBody.length) {
    const ch = arrayBody[i]
    if (ch === '"' || ch === "'") {
      i = skipQuoted(arrayBody, i)
      continue
    }
    if (ch === "`") {
      i = skipTemplate(arrayBody, i)
      continue
    }
    if (ch === "/") {
      const skipped = skipComment(arrayBody, i)
      if (skipped !== i) {
        i = skipped
        continue
      }
    }
    if (ch === "{") {
      const close = findMatching(arrayBody, i)
      if (close === -1) break
      contributions.push(parseContribution(arrayBody.slice(i + 1, close), defaults))
      i = close + 1
      continue
    }
    i++
  }
  return contributions
}

function parseContribution(
  objectBody: string,
  defaults: Map<string, string>,
): ScannedRouteContribution {
  const contribution: ScannedRouteContribution = {
    id: null,
    path: null,
    rawPath: null,
    hasComponent: false,
    hasLoader: false,
    hasValidateSearch: false,
    ssr: null,
    preload: null,
  }

  for (const entry of splitTopLevel(objectBody)) {
    const keyMatch = /^([A-Za-z_$][\w$]*)\s*(:)?/.exec(entry)
    if (!keyMatch) continue
    const key = keyMatch[1]
    const hasColon = keyMatch[2] === ":"
    const value = hasColon ? entry.slice(keyMatch[0].length).trim() : null

    switch (key) {
      case "id":
        contribution.id = value === null ? null : stringLiteralValue(value)
        break
      case "path": {
        // Shorthand `path,` resolves through the destructuring default.
        const raw = value ?? "path"
        contribution.rawPath = raw
        contribution.path = resolvePathValue(raw, defaults)
        break
      }
      case "component":
        contribution.hasComponent = true
        break
      case "loader":
        contribution.hasLoader = true
        break
      case "validateSearch":
        contribution.hasValidateSearch = true
        break
      case "ssr": {
        if (value === "true") contribution.ssr = true
        else if (value === "false") contribution.ssr = false
        else if (value !== null && stringLiteralValue(value) === "data-only") {
          contribution.ssr = "data-only"
        }
        break
      }
      case "preload": {
        if (value === "false") contribution.preload = false
        else if (value !== null) contribution.preload = stringLiteralValue(value)
        break
      }
      default:
        break
    }
  }
  return contribution
}

// ---------------------------------------------------------------------------
// Destination scanning (doctor Finding D)
// ---------------------------------------------------------------------------

/**
 * Destination keys an admin entry declares via
 * `declare module "@voyantjs/admin" { interface AdminDestinations { ... } }`.
 */
export function scanDeclaredDestinationKeys(source: string): string[] {
  const keys = new Set<string>()
  const modulePattern = /declare\s+module\s+["']@voyantjs\/admin["']/g
  let moduleMatch: RegExpExecArray | null = modulePattern.exec(source)
  while (moduleMatch !== null) {
    const moduleOpen = source.indexOf("{", moduleMatch.index + moduleMatch[0].length - 1)
    if (moduleOpen !== -1) {
      const moduleClose = findMatching(source, moduleOpen)
      if (moduleClose !== -1) {
        const moduleBody = source.slice(moduleOpen + 1, moduleClose)
        const interfaceMatch = /interface\s+AdminDestinations\b/.exec(moduleBody)
        if (interfaceMatch) {
          const interfaceOpen = moduleBody.indexOf(
            "{",
            interfaceMatch.index + interfaceMatch[0].length,
          )
          if (interfaceOpen !== -1) {
            const interfaceClose = findMatching(moduleBody, interfaceOpen)
            if (interfaceClose !== -1) {
              for (const key of scanTopLevelQuotedKeys(
                moduleBody.slice(interfaceOpen + 1, interfaceClose),
              )) {
                keys.add(key)
              }
            }
          }
        }
      }
    }
    moduleMatch = modulePattern.exec(source)
  }
  return [...keys]
}

/**
 * Keys of the host's destination resolver map — the object literal followed
 * by `satisfies AdminDestinationResolvers`. Returns null when no such map is
 * found in the source (so callers can tell "no map" apart from "empty map").
 */
export function scanResolverMapKeys(source: string): string[] | null {
  const pattern = /=\s*\{/g
  let match: RegExpExecArray | null = pattern.exec(source)
  while (match !== null) {
    const open = match.index + match[0].length - 1
    const close = findMatching(source, open)
    if (close !== -1) {
      const after = source.slice(close + 1)
      if (/^\s*satisfies\s+AdminDestinationResolvers\b/.test(after)) {
        return scanTopLevelQuotedKeys(source.slice(open + 1, close))
      }
    }
    match = pattern.exec(source)
  }
  return null
}

// ---------------------------------------------------------------------------
// Route-file paths + rendering
// ---------------------------------------------------------------------------

/**
 * The createFileRoute id for a contribution path hosted under `routesDir`
 * (relative to the config dir, e.g. "src/routes/_workspace"): the dir's
 * segments after `routes` become the tree prefix, and index files keep the
 * trailing slash (`/_workspace/promotions/`).
 */
export function fileRouteIdFor(routesDirRel: string, routePath: string): string {
  const segments = routesDirRel.split(/[\\/]/).filter(Boolean)
  const routesIndex = segments.lastIndexOf("routes")
  const prefixSegments = routesIndex === -1 ? [] : segments.slice(routesIndex + 1)
  const prefix = prefixSegments.length > 0 ? `/${prefixSegments.join("/")}` : ""
  return `${prefix}${routePath}/`
}

/** Canonical generated-file location for a contribution path: `<rel>/index.tsx`. */
export function canonicalRouteFileRelPath(routePath: string): string {
  return join(...routePath.replace(/^\//, "").split("/"), "index.tsx")
}

/**
 * Alternative file-routing spellings a hand-written host for `routePath`
 * may already use. Any existing one means the route is already bound and the
 * generator must not create a parallel file.
 */
export function alternativeRouteFileRelPaths(routePath: string): string[] {
  const rel = routePath.replace(/^\//, "")
  const dotted = rel.replaceAll("/", ".")
  const segments = rel.split("/")
  return [
    `${join(...segments)}.tsx`,
    `${join(...segments)}.ts`,
    join(...segments, "index.ts"),
    join(...segments, "route.tsx"),
    `${dotted}.tsx`,
    `${dotted}.index.tsx`,
  ]
}

export interface RenderRouteFileOptions {
  /** createFileRoute id, e.g. `/_workspace/promotions/`. */
  fileRouteId: string
  /** Admin entry import specifier, e.g. `@voyantjs/promotions-ui/admin`. */
  importSpec: string
  /** Extension factory export, e.g. `createPromotionsAdminExtension`. */
  exportName: string
  /** Route contribution id, e.g. `promotions-index`. */
  routeId: string
  ssr: boolean | "data-only" | null
  preload: string | false | null
  hasLoader: boolean
  hasValidateSearch: boolean
  runtime: AdminRouteRuntimeImports
}

/**
 * Render a generated thin route file: resolve the contribution through
 * `requireAdminRoute` and bind it to the host's file-based route tree with
 * the app runtime — exactly what the hand-written thin hosts do. Output is
 * deterministic so `--check` stays a pure string comparison.
 */
export function renderRouteFile(options: RenderRouteFileOptions): string {
  const { fileRouteId, importSpec, exportName, routeId, ssr, preload, runtime } = options

  const imports = [
    `import { createFileRoute } from "@tanstack/react-router"`,
    `import { requireAdminRoute } from "@voyantjs/admin"`,
    `import { ${exportName} } from "${importSpec}"`,
  ]
  if (options.hasLoader) {
    imports.push(
      `import { ${runtime.apiUrlExport} } from "${runtime.apiUrlModule}"`,
      `import { ${runtime.fetcherExport} } from "${runtime.fetcherModule}"`,
    )
  }

  const routeOptions: string[] = []
  if (ssr !== null) {
    routeOptions.push(`  ssr: ${typeof ssr === "string" ? JSON.stringify(ssr) : String(ssr)},`)
  }
  if (preload !== null) {
    routeOptions.push(`  preload: ${preload === false ? "false" : JSON.stringify(preload)},`)
  }
  if (options.hasValidateSearch) {
    routeOptions.push(`  validateSearch: route.validateSearch,`)
  }
  if (options.hasLoader) {
    routeOptions.push(
      `  loader: ({ context }) =>`,
      `    route.loader?.({`,
      `      queryClient: context.queryClient,`,
      `      runtime: { baseUrl: ${runtime.apiUrlExport}(), fetcher: ${runtime.fetcherExport} },`,
      `    }),`,
    )
  }
  routeOptions.push(`  component: RouteComponent,`)

  return [
    `${GENERATED_ROUTE_HEADER} — do not edit.`,
    `// Thin host for the package-delivered ${importSpec} route "${routeId}"`,
    `// (packaged-admin RFC §4.2): page, loader, and SSR mode are package-owned;`,
    `// this file only binds them into the host's file-based route tree with the`,
    `// app runtime. Recreate with \`voyant admin generate --routes\`.`,
    `// To eject and hand-maintain this host, delete this header — the generator`,
    `// skips files without it.`,
    ...imports,
    ``,
    `const route = requireAdminRoute(${exportName}(), "${routeId}")`,
    `// Top-level identifier on purpose: the router's code-splitter can extract`,
    `// an identifier binding, but not a member expression.`,
    `const RouteComponent = route.component`,
    ``,
    `export const Route = createFileRoute("${fileRouteId}")({`,
    ...routeOptions,
    `})`,
    ``,
  ].join("\n")
}
