import type { LinkDefinition } from "@voyantjs/core/links"

/**
 * Render a Drizzle schema module that defines a `pgTable` for each materialized
 * link, mirroring exactly the columns + cardinality-aware indexes that
 * `generateLinkTableSql` emits. Feeding this generated module into a template's
 * schema set makes link tables participate in Drizzle's diff/snapshot — so they
 * are migrated and drift-checked like any other table, instead of being applied
 * out-of-band by `voyant db sync-links` (raw `CREATE TABLE IF NOT EXISTS`).
 *
 * Read-only (externally-owned) links materialize no table and are skipped.
 */
export function renderLinkDrizzleSchema(links: LinkDefinition[]): string {
  const materialized = links.filter((link) => !link.readOnly)

  const header = [
    "// AUTO-GENERATED by `voyant db sync-links --emit-drizzle`.",
    "// Drizzle table definitions for cross-module link (pivot) tables, derived",
    "// from the template's link definitions. Do not edit by hand — re-run the",
    "// command to refresh. `voyant db doctor` fails if a link table is missing",
    "// from the migration snapshot.",
    'import { sql } from "drizzle-orm"',
    'import { index, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core"',
    "",
  ].join("\n")

  if (materialized.length === 0) {
    return `${header}// No materialized link tables.\n`
  }

  return `${header}${materialized.map(renderOne).join("\n\n")}\n`
}

function renderOne(def: LinkDefinition): string {
  const { tableName, leftColumn, rightColumn } = def
  const exportName = toIdentifier(tableName)
  const where = 'sql`"deleted_at" IS NULL`'

  // Index builders mirror generateLinkTableSql exactly (names + uniqueness).
  const indexLines: string[] = [
    `    uniqueIndex(${q(`${tableName}_pair_idx`)}).on(t[${q(leftColumn)}], t[${q(rightColumn)}]).where(${where}),`,
    def.right.isList
      ? `    index(${q(`${tableName}_l_idx`)}).on(t[${q(leftColumn)}]).where(${where}),`
      : `    uniqueIndex(${q(`${tableName}_l_uniq`)}).on(t[${q(leftColumn)}]).where(${where}),`,
    def.left.isList
      ? `    index(${q(`${tableName}_r_idx`)}).on(t[${q(rightColumn)}]).where(${where}),`
      : `    uniqueIndex(${q(`${tableName}_r_uniq`)}).on(t[${q(rightColumn)}]).where(${where}),`,
  ]

  return [
    `export const ${exportName} = pgTable(`,
    `  ${q(tableName)},`,
    "  {",
    `    id: text("id").primaryKey().notNull(),`,
    `    ${q(leftColumn)}: text(${q(leftColumn)}).notNull(),`,
    `    ${q(rightColumn)}: text(${q(rightColumn)}).notNull(),`,
    `    created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),`,
    `    updated_at: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),`,
    `    deleted_at: timestamp("deleted_at", { withTimezone: true }),`,
    "  },",
    "  (t) => [",
    ...indexLines,
    "  ],",
    ")",
  ].join("\n")
}

function q(value: string): string {
  return JSON.stringify(value)
}

/** Make a safe JS identifier for the export name (link table names are already snake/camel). */
function toIdentifier(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9_$]/g, "_")
  return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned
}
