import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, isAbsolute, relative, resolve as resolvePath } from "node:path"

import { resolveSchemas, type SchemaResolutionStyle } from "./resolve-schemas.js"
import type { SchemaManifestConfig } from "./voyant-config.js"

/** Default filename for the committed, generated schema list. */
export const GENERATED_SCHEMA_FILENAME = "drizzle.schemas.generated.ts"

export interface SchemaManifestOptions {
  /** Template/app directory the manifest is resolved against. */
  cwd: string
  /** Output style for the entries (defaults to "specifier"). */
  style?: SchemaResolutionStyle
}

export interface RenderOptions {
  /** Template/app directory the manifest is resolved against. */
  cwd: string
  /** Output path for the generated file (defaults to `<cwd>/<filename>`). */
  outPath?: string
}

export interface GeneratedSchemaManifest {
  /** Absolute path the manifest is (or would be) written to. */
  path: string
  /** Full file contents. */
  content: string
  /** The schema entries, as portable relative paths from the file's dir. */
  entries: string[]
}

/**
 * The full ordered schema list for a template: the package-derived dependency
 * closure ({@link resolveSchemas}, seeded from `modules` + `additionalSchemas`)
 * followed by any template-**local** `schemas` (deployment-owned glue that
 * belongs to no package, e.g. operator's `./src/db/schema.ts`).
 */
export function resolveSchemaManifest(
  config: SchemaManifestConfig,
  options: SchemaManifestOptions,
): string[] {
  const style = options.style ?? "specifier"
  const packageSchemas = resolveSchemas(config, { cwd: options.cwd, style })
  const localSchemas = (config.schemas ?? []).map((entry) =>
    style === "file" ? toAbsolute(options.cwd, entry) : entry,
  )
  return [...packageSchemas, ...localSchemas]
}

/**
 * Render the generated `drizzle.schemas.generated.ts` content. Entries are
 * emitted as POSIX relative paths from the generated file's directory so the
 * file is portable across machines and diff-friendly in review.
 */
export function renderSchemaManifest(
  config: SchemaManifestConfig,
  options: RenderOptions,
): GeneratedSchemaManifest {
  const outPath = options.outPath
    ? toAbsolute(options.cwd, options.outPath)
    : resolvePath(options.cwd, GENERATED_SCHEMA_FILENAME)
  const outDir = dirname(outPath)

  const absoluteEntries = resolveSchemaManifest(config, { cwd: options.cwd, style: "file" })
  const entries = absoluteEntries.map((entry) => toPortableRelative(outDir, entry))

  const body = entries.map((entry) => `  ${JSON.stringify(entry)},`).join("\n")
  const content =
    "// AUTO-GENERATED by `voyant db schemas --emit` (or `voyant db generate`).\n" +
    "// Source of truth: voyant.config.ts (modules + additionalSchemas + schemas).\n" +
    "// Do not edit by hand — re-run the command to refresh.\n" +
    "export const schema = [\n" +
    `${body}\n` +
    "] as const\n"

  return { path: outPath, content, entries }
}

/** Render and write the generated manifest to disk. */
export function writeSchemaManifest(
  config: SchemaManifestConfig,
  options: RenderOptions,
): GeneratedSchemaManifest {
  const generated = renderSchemaManifest(config, options)
  writeFileSync(generated.path, generated.content)
  return generated
}

/** Read the on-disk generated manifest, or `null` when absent. */
export function readSchemaManifest(path: string): string | null {
  if (!existsSync(path)) return null
  return readFileSync(path, "utf8")
}

function toAbsolute(cwd: string, entry: string): string {
  return isAbsolute(entry) ? entry : resolvePath(cwd, entry)
}

function toPortableRelative(fromDir: string, absPath: string): string {
  const rel = relative(fromDir, absPath).replaceAll("\\", "/")
  return rel.startsWith(".") ? rel : `./${rel}`
}
