import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { afterEach, beforeEach, describe, expect, it } from "vitest"

import { adminGenerateCommand } from "../../src/commands/admin-generate.js"

function makeCtx(argv: string[], cwd: string) {
  const stdout: string[] = []
  const stderr: string[] = []
  return {
    ctx: {
      argv,
      cwd,
      stdout: (chunk: string) => stdout.push(chunk),
      stderr: (chunk: string) => stderr.push(chunk),
    },
    stdout,
    stderr,
  }
}

/** Write a fake installed package into `<root>/node_modules/<name>/`. */
function writePackage(
  root: string,
  name: string,
  pkg: Record<string, unknown>,
  files: Record<string, string> = {},
) {
  const dir = join(root, "node_modules", ...name.split("/"))
  mkdirSync(dir, { recursive: true })
  writeFileSync(join(dir, "package.json"), JSON.stringify({ name, version: "0.0.0", ...pkg }))
  for (const [rel, content] of Object.entries(files)) {
    const abs = join(dir, rel)
    mkdirSync(join(abs, ".."), { recursive: true })
    writeFileSync(abs, content)
  }
}

const FOO_ADMIN_SOURCE = `
export function createFooAdminExtension(options = {}) {
  return {
    id: "foo",
    navigation: [],
    routes: [{ id: "foo-index", path: "/foo" }],
  }
}
`

/**
 * Fixture: a manifest mounting @voyantjs/foo (which has a conventional
 * @voyantjs/foo-ui/admin entry) and @voyantjs/bar (no ui package at all).
 */
function writeFixture(root: string) {
  writeFileSync(
    join(root, "voyant.config.ts"),
    `export default { modules: ["@voyantjs/foo", "@voyantjs/bar"] }\n`,
  )
  writePackage(root, "@voyantjs/foo", { exports: { ".": "./src/index.ts" } })
  writePackage(
    root,
    "@voyantjs/foo-ui",
    { exports: { ".": "./src/index.ts", "./admin": "./src/admin/index.tsx" } },
    { "src/admin/index.tsx": FOO_ADMIN_SOURCE },
  )
  writePackage(root, "@voyantjs/bar", { exports: { ".": "./src/index.ts" } })
}

describe("adminGenerateCommand", () => {
  let tmp: string

  beforeEach(() => {
    tmp = mkdtempSync(join(tmpdir(), "voyant-cli-admin-generate-"))
  })

  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true })
  })

  it("fails when no config file is found", async () => {
    const { ctx, stderr } = makeCtx([], tmp)
    const code = await adminGenerateCommand(ctx)
    expect(code).toBe(1)
    expect(stderr.join("")).toContain("No voyant.config.* found")
  })

  it("writes the generated composition file with one factory per admin entry", async () => {
    writeFixture(tmp)
    const { ctx, stdout } = makeCtx([], tmp)
    const code = await adminGenerateCommand(ctx)
    expect(code).toBe(0)

    const outPath = join(tmp, "src", "admin.extensions.generated.ts")
    expect(existsSync(outPath)).toBe(true)
    const content = readFileSync(outPath, "utf8")
    expect(content).toContain("GENERATED by voyant admin generate — do not edit")
    expect(content).toContain(`import { createFooAdminExtension } from "@voyantjs/foo-ui/admin"`)
    expect(content).toContain("export const generatedAdminExtensionFactories = {")
    expect(content).toContain("foo: createFooAdminExtension,")
    expect(content).toContain("} as const")
    expect(stdout.join("")).toContain("2 modules, 1 admin entries, wrote")
  })

  it("skips modules without an admin entry and notes them", async () => {
    writeFixture(tmp)
    const { ctx, stderr } = makeCtx([], tmp)
    await adminGenerateCommand(ctx)

    const content = readFileSync(join(tmp, "src", "admin.extensions.generated.ts"), "utf8")
    expect(content).not.toContain("@voyantjs/bar")
    expect(stderr.join("")).toContain("[admin-generate]")
    expect(stderr.join("")).toContain("@voyantjs/bar")
  })

  it("warns and skips when the admin entry lacks the conventional export", async () => {
    writeFixture(tmp)
    writeFileSync(
      join(tmp, "node_modules", "@voyantjs", "foo-ui", "src", "admin", "index.tsx"),
      `export function createSomethingElse() {}\n`,
    )
    const { ctx, stderr } = makeCtx([], tmp)
    const code = await adminGenerateCommand(ctx)
    expect(code).toBe(0)

    const content = readFileSync(join(tmp, "src", "admin.extensions.generated.ts"), "utf8")
    expect(content).not.toContain("@voyantjs/foo-ui/admin")
    expect(stderr.join("")).toContain("does not export createFooAdminExtension")
  })

  it("honors a package.json voyant.adminEntry override", async () => {
    writeFileSync(join(tmp, "voyant.config.ts"), `export default { modules: ["@voyantjs/baz"] }\n`)
    writePackage(tmp, "@voyantjs/baz", {
      exports: { ".": "./src/index.ts" },
      voyant: { adminEntry: "@voyantjs/baz-admin/entry" },
    })
    writePackage(
      tmp,
      "@voyantjs/baz-admin",
      { exports: { "./entry": "./src/entry.tsx" } },
      { "src/entry.tsx": `export function createBazAdminExtension() {}\n` },
    )

    const { ctx } = makeCtx([], tmp)
    const code = await adminGenerateCommand(ctx)
    expect(code).toBe(0)
    const content = readFileSync(join(tmp, "src", "admin.extensions.generated.ts"), "utf8")
    expect(content).toContain(`import { createBazAdminExtension } from "@voyantjs/baz-admin/entry"`)
    expect(content).toContain("baz: createBazAdminExtension,")
  })

  it("--check exits 1 when the file is missing", async () => {
    writeFixture(tmp)
    const { ctx, stderr } = makeCtx(["--check"], tmp)
    const code = await adminGenerateCommand(ctx)
    expect(code).toBe(1)
    expect(stderr.join("")).toContain("is missing")
    expect(existsSync(join(tmp, "src", "admin.extensions.generated.ts"))).toBe(false)
  })

  it("--check detects drift and passes once regenerated", async () => {
    writeFixture(tmp)
    mkdirSync(join(tmp, "src"), { recursive: true })
    writeFileSync(join(tmp, "src", "admin.extensions.generated.ts"), "// stale\n")

    const drift = makeCtx(["--check"], tmp)
    expect(await adminGenerateCommand(drift.ctx)).toBe(1)
    expect(drift.stderr.join("")).toContain("out of date")
    // --check must not rewrite the file.
    expect(readFileSync(join(tmp, "src", "admin.extensions.generated.ts"), "utf8")).toBe(
      "// stale\n",
    )

    expect(await adminGenerateCommand(makeCtx([], tmp).ctx)).toBe(0)
    const clean = makeCtx(["--check"], tmp)
    expect(await adminGenerateCommand(clean.ctx)).toBe(0)
    expect(clean.stdout.join("")).toContain("up to date")
  })

  it("respects --out relative to cwd", async () => {
    writeFixture(tmp)
    const { ctx } = makeCtx(["--out", "generated/admin.ts"], tmp)
    const code = await adminGenerateCommand(ctx)
    expect(code).toBe(0)
    expect(existsSync(join(tmp, "generated", "admin.ts"))).toBe(true)
  })
})
