import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { afterEach, beforeEach, describe, expect, it } from "vitest"

import { adminGenerateCommand } from "../../src/commands/admin-generate.js"

function makeCtx(argv: string[], cwd: string) {
  const stdout: string[] = []
  const stderr: string[] = []
  return {
    ctx: {
      argv,
      cwd,
      stdout: (chunk: string) => stdout.push(chunk),
      stderr: (chunk: string) => stderr.push(chunk),
    },
    stdout,
    stderr,
  }
}

/** Write a fake installed package into `<root>/node_modules/<name>/`. */
function writePackage(
  root: string,
  name: string,
  pkg: Record<string, unknown>,
  files: Record<string, string> = {},
) {
  const dir = join(root, "node_modules", ...name.split("/"))
  mkdirSync(dir, { recursive: true })
  writeFileSync(join(dir, "package.json"), JSON.stringify({ name, version: "0.0.0", ...pkg }))
  for (const [rel, content] of Object.entries(files)) {
    const abs = join(dir, rel)
    mkdirSync(join(abs, ".."), { recursive: true })
    writeFileSync(abs, content)
  }
}

const FOO_ADMIN_SOURCE = `
export function createFooAdminExtension(options = {}) {
  return {
    id: "foo",
    navigation: [],
    routes: [{ id: "foo-index", path: "/foo" }],
  }
}
`

/**
 * Fixture: a manifest mounting @voyantjs/foo (which has a conventional
 * @voyantjs/foo-react/admin entry) and @voyantjs/bar (no ui package at all).
 */
function writeFixture(root: string) {
  writeFileSync(
    join(root, "voyant.config.ts"),
    `export default { modules: ["@voyantjs/foo", "@voyantjs/bar"] }\n`,
  )
  writePackage(root, "@voyantjs/foo", { exports: { ".": "./src/index.ts" } })
  writePackage(
    root,
    "@voyantjs/foo-react",
    { exports: { ".": "./src/index.ts", "./admin": "./src/admin/index.tsx" } },
    { "src/admin/index.tsx": FOO_ADMIN_SOURCE },
  )
  writePackage(root, "@voyantjs/bar", { exports: { ".": "./src/index.ts" } })
}

describe("adminGenerateCommand", () => {
  let tmp: string

  beforeEach(() => {
    tmp = mkdtempSync(join(tmpdir(), "voyant-cli-admin-generate-"))
  })

  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true })
  })

  it("fails when no config file is found", async () => {
    const { ctx, stderr } = makeCtx([], tmp)
    const code = await adminGenerateCommand(ctx)
    expect(code).toBe(1)
    expect(stderr.join("")).toContain("No voyant.config.* found")
  })

  it("writes the generated composition file with one factory per admin entry", async () => {
    writeFixture(tmp)
    const { ctx, stdout } = makeCtx([], tmp)
    const code = await adminGenerateCommand(ctx)
    expect(code).toBe(0)

    const outPath = join(tmp, "src", "admin.extensions.generated.ts")
    expect(existsSync(outPath)).toBe(true)
    const content = readFileSync(outPath, "utf8")
    expect(content).toContain("GENERATED by voyant admin generate — do not edit")
    expect(content).toContain(`import { createFooAdminExtension } from "@voyantjs/foo-react/admin"`)
    expect(content).toContain("export const generatedAdminExtensionFactories = {")
    expect(content).toContain("foo: createFooAdminExtension,")
    expect(content).toContain("} as const")
    expect(stdout.join("")).toContain("2 modules, 1 admin entries, wrote")
  })

  it("skips modules without an admin entry and notes them", async () => {
    writeFixture(tmp)
    const { ctx, stderr } = makeCtx([], tmp)
    await adminGenerateCommand(ctx)

    const content = readFileSync(join(tmp, "src", "admin.extensions.generated.ts"), "utf8")
    expect(content).not.toContain("@voyantjs/bar")
    expect(stderr.join("")).toContain("[admin-generate]")
    expect(stderr.join("")).toContain("@voyantjs/bar")
  })

  it("warns and skips when the admin entry lacks the conventional export", async () => {
    writeFixture(tmp)
    writeFileSync(
      join(tmp, "node_modules", "@voyantjs", "foo-react", "src", "admin", "index.tsx"),
      `export function createSomethingElse() {}\n`,
    )
    const { ctx, stderr } = makeCtx([], tmp)
    const code = await adminGenerateCommand(ctx)
    expect(code).toBe(0)

    const content = readFileSync(join(tmp, "src", "admin.extensions.generated.ts"), "utf8")
    expect(content).not.toContain("@voyantjs/foo-react/admin")
    expect(stderr.join("")).toContain("does not export createFooAdminExtension")
  })

  it("honors a package.json voyant.adminEntry override", async () => {
    writeFileSync(join(tmp, "voyant.config.ts"), `export default { modules: ["@voyantjs/baz"] }\n`)
    writePackage(tmp, "@voyantjs/baz", {
      exports: { ".": "./src/index.ts" },
      voyant: { adminEntry: "@voyantjs/baz-admin/entry" },
    })
    writePackage(
      tmp,
      "@voyantjs/baz-admin",
      { exports: { "./entry": "./src/entry.tsx" } },
      { "src/entry.tsx": `export function createBazAdminExtension() {}\n` },
    )

    const { ctx } = makeCtx([], tmp)
    const code = await adminGenerateCommand(ctx)
    expect(code).toBe(0)
    const content = readFileSync(join(tmp, "src", "admin.extensions.generated.ts"), "utf8")
    expect(content).toContain(`import { createBazAdminExtension } from "@voyantjs/baz-admin/entry"`)
    expect(content).toContain("baz: createBazAdminExtension,")
  })

  it("--check exits 1 when the file is missing", async () => {
    writeFixture(tmp)
    const { ctx, stderr } = makeCtx(["--check"], tmp)
    const code = await adminGenerateCommand(ctx)
    expect(code).toBe(1)
    expect(stderr.join("")).toContain("is missing")
    expect(existsSync(join(tmp, "src", "admin.extensions.generated.ts"))).toBe(false)
  })

  it("--check detects drift and passes once regenerated", async () => {
    writeFixture(tmp)
    mkdirSync(join(tmp, "src"), { recursive: true })
    writeFileSync(join(tmp, "src", "admin.extensions.generated.ts"), "// stale\n")

    const drift = makeCtx(["--check"], tmp)
    expect(await adminGenerateCommand(drift.ctx)).toBe(1)
    expect(drift.stderr.join("")).toContain("out of date")
    // --check must not rewrite the file.
    expect(readFileSync(join(tmp, "src", "admin.extensions.generated.ts"), "utf8")).toBe(
      "// stale\n",
    )

    expect(await adminGenerateCommand(makeCtx([], tmp).ctx)).toBe(0)
    const clean = makeCtx(["--check"], tmp)
    expect(await adminGenerateCommand(clean.ctx)).toBe(0)
    expect(clean.stdout.join("")).toContain("up to date")
  })

  it("respects --out relative to cwd", async () => {
    writeFixture(tmp)
    const { ctx } = makeCtx(["--out", "generated/admin.ts"], tmp)
    const code = await adminGenerateCommand(ctx)
    expect(code).toBe(0)
    expect(existsSync(join(tmp, "generated", "admin.ts"))).toBe(true)
  })
})

const FOO_ADMIN_ROUTES_SOURCE = `
import { defineAdminExtension } from "@voyantjs/admin"
import { FooPage, loadFooPage } from "../foo-page.js"

export function createFooAdminExtension(options = {}) {
  const { label = "Foo", path = "/foo" } = options
  return defineAdminExtension({
    id: "foo",
    routes: [
      {
        id: "foo-index",
        path,
        title: label,
        ssr: "data-only",
        component: FooPage,
        loader: ({ queryClient, runtime }) =>
          loadFooPage(queryClient, { baseUrl: runtime.baseUrl, fetcher: runtime.fetcher }),
      },
      {
        id: "foo-detail",
        path: \`\${path}/$fooId\`,
        title: label,
        component: FooDetailPage,
      },
      {
        id: "foo-metadata-only",
        path: "/foo-meta",
        title: label,
      },
    ],
  })
}
`

/** Fixture whose admin entry carries one zero-prop route implementation. */
function writeRoutesFixture(root: string) {
  writeFileSync(join(root, "voyant.config.ts"), `export default { modules: ["@voyantjs/foo"] }\n`)
  writePackage(root, "@voyantjs/foo", { exports: { ".": "./src/index.ts" } })
  writePackage(
    root,
    "@voyantjs/foo-react",
    { exports: { ".": "./src/index.ts", "./admin": "./src/admin/index.tsx" } },
    { "src/admin/index.tsx": FOO_ADMIN_ROUTES_SOURCE },
  )
}

describe("adminGenerateCommand --routes", () => {
  let tmp: string

  beforeEach(() => {
    tmp = mkdtempSync(join(tmpdir(), "voyant-cli-admin-routes-"))
  })

  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true })
  })

  const generatedPath = () => join(tmp, "src", "routes", "_workspace", "foo", "index.tsx")

  it("emits a generated thin route file for a zero-prop contribution only", async () => {
    writeRoutesFixture(tmp)
    const { ctx, stdout } = makeCtx(["--routes"], tmp)
    const code = await adminGenerateCommand(ctx)
    expect(code).toBe(0)

    const content = readFileSync(generatedPath(), "utf8")
    expect(content.startsWith("// GENERATED by voyant admin generate --routes")).toBe(true)
    expect(content).toContain(`import { requireAdminRoute } from "@voyantjs/admin"`)
    expect(content).toContain(`import { createFooAdminExtension } from "@voyantjs/foo-react/admin"`)
    expect(content).toContain(`import { getApiUrl } from "@/lib/env"`)
    expect(content).toContain(`import { operatorFetcher } from "@/lib/voyant-fetcher"`)
    expect(content).toContain(
      `const route = requireAdminRoute(createFooAdminExtension(), "foo-index")`,
    )
    expect(content).toContain(`createFileRoute("/_workspace/foo/")`)
    expect(content).toContain(`ssr: "data-only",`)
    expect(content).toContain(`component: RouteComponent,`)

    // The param-taking detail host and the metadata-only contribution are not emitted.
    expect(existsSync(join(tmp, "src", "routes", "_workspace", "foo", "$fooId.tsx"))).toBe(false)
    expect(existsSync(join(tmp, "src", "routes", "_workspace", "foo-meta"))).toBe(false)
    expect(stdout.join("")).toContain(
      "1 param route(s) and 1 metadata-only contribution(s) left to hand-written hosts",
    )
    expect(stdout.join("")).toContain("1 written")
  })

  it("honors the manifest admin.routes runtime-import config", async () => {
    writeRoutesFixture(tmp)
    writeFileSync(
      join(tmp, "voyant.config.ts"),
      [
        `export default {`,
        `  modules: ["@voyantjs/foo"],`,
        `  admin: {`,
        `    routes: {`,
        `      apiUrlModule: "~/runtime/env",`,
        `      apiUrlExport: "apiUrl",`,
        `      fetcherModule: "~/runtime/fetch",`,
        `      fetcherExport: "appFetcher",`,
        `    },`,
        `  },`,
        `}`,
        ``,
      ].join("\n"),
    )
    const { ctx } = makeCtx(["--routes"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
    const content = readFileSync(generatedPath(), "utf8")
    expect(content).toContain(`import { apiUrl } from "~/runtime/env"`)
    expect(content).toContain(`import { appFetcher } from "~/runtime/fetch"`)
    expect(content).toContain(`runtime: { baseUrl: apiUrl(), fetcher: appFetcher },`)
  })

  it("never overwrites a hand-written file lacking the generated header (ejection)", async () => {
    writeRoutesFixture(tmp)
    mkdirSync(join(tmp, "src", "routes", "_workspace", "foo"), { recursive: true })
    const handWritten = `// hand-written host\nexport const Route = {}\n`
    writeFileSync(generatedPath(), handWritten)

    const { ctx, stderr, stdout } = makeCtx(["--routes"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
    expect(readFileSync(generatedPath(), "utf8")).toBe(handWritten)
    expect(stderr.join("")).toContain("ejected, hand-written host")
    expect(stdout.join("")).toContain("1 ejected")
  })

  it("skips when a hand-written host exists under another file-routing spelling", async () => {
    writeRoutesFixture(tmp)
    mkdirSync(join(tmp, "src", "routes", "_workspace"), { recursive: true })
    writeFileSync(
      join(tmp, "src", "routes", "_workspace", "foo.tsx"),
      `// flat hand-written host\n`,
    )

    const { ctx, stderr } = makeCtx(["--routes"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
    expect(existsSync(generatedPath())).toBe(false)
    expect(stderr.join("")).toContain("already binds this route")
  })

  it("--check reports drift for missing and stale files, passes when regenerated", async () => {
    writeRoutesFixture(tmp)

    const missing = makeCtx(["--routes", "--check"], tmp)
    expect(await adminGenerateCommand(missing.ctx)).toBe(1)
    expect(missing.stderr.join("")).toContain("is missing")
    expect(existsSync(generatedPath())).toBe(false)

    expect(await adminGenerateCommand(makeCtx(["--routes"], tmp).ctx)).toBe(0)
    const clean = makeCtx(["--routes", "--check"], tmp)
    expect(await adminGenerateCommand(clean.ctx)).toBe(0)
    expect(clean.stdout.join("")).toContain("1 up to date")

    writeFileSync(
      generatedPath(),
      `// GENERATED by voyant admin generate --routes — do not edit.\n// stale\n`,
    )
    const drift = makeCtx(["--routes", "--check"], tmp)
    expect(await adminGenerateCommand(drift.ctx)).toBe(1)
    expect(drift.stderr.join("")).toContain("is out of date")
  })

  it("--check treats ejected files as fine", async () => {
    writeRoutesFixture(tmp)
    mkdirSync(join(tmp, "src", "routes", "_workspace", "foo"), { recursive: true })
    writeFileSync(generatedPath(), `// hand-written host\n`)
    const { ctx } = makeCtx(["--routes", "--check"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
  })

  it("respects --routes-dir", async () => {
    writeRoutesFixture(tmp)
    const { ctx } = makeCtx(["--routes", "--routes-dir", "app/routes/admin"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
    const content = readFileSync(join(tmp, "app", "routes", "admin", "foo", "index.tsx"), "utf8")
    expect(content).toContain(`createFileRoute("/admin/foo/")`)
  })
})
