import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { afterEach, beforeEach, describe, expect, it } from "vitest"

import { adminGenerateCommand } from "../../src/commands/admin-generate.js"

function makeCtx(argv: string[], cwd: string) {
  const stdout: string[] = []
  const stderr: string[] = []
  return {
    ctx: {
      argv,
      cwd,
      stdout: (chunk: string) => stdout.push(chunk),
      stderr: (chunk: string) => stderr.push(chunk),
    },
    stdout,
    stderr,
  }
}

/** Write a fake installed package into `<root>/node_modules/<name>/`. */
function writePackage(
  root: string,
  name: string,
  pkg: Record<string, unknown>,
  files: Record<string, string> = {},
) {
  const dir = join(root, "node_modules", ...name.split("/"))
  mkdirSync(dir, { recursive: true })
  writeFileSync(join(dir, "package.json"), JSON.stringify({ name, version: "0.0.0", ...pkg }))
  for (const [rel, content] of Object.entries(files)) {
    const abs = join(dir, rel)
    mkdirSync(join(abs, ".."), { recursive: true })
    writeFileSync(abs, content)
  }
}

const FOO_ADMIN_SOURCE = `
export function createFooAdminExtension(options = {}) {
  return {
    id: "foo",
    navigation: [],
    routes: [{ id: "foo-index", path: "/foo" }],
  }
}
`

/**
 * Fixture: a manifest mounting @voyantjs/foo (which has a conventional
 * @voyantjs/foo-react/admin entry) and @voyantjs/bar (no ui package at all).
 */
function writeFixture(root: string) {
  writeFileSync(
    join(root, "voyant.config.ts"),
    `export default { modules: ["@voyantjs/foo", "@voyantjs/bar"] }\n`,
  )
  writePackage(root, "@voyantjs/foo", { exports: { ".": "./src/index.ts" } })
  writePackage(
    root,
    "@voyantjs/foo-react",
    { exports: { ".": "./src/index.ts", "./admin": "./src/admin/index.tsx" } },
    { "src/admin/index.tsx": FOO_ADMIN_SOURCE },
  )
  writePackage(root, "@voyantjs/bar", { exports: { ".": "./src/index.ts" } })
}

describe("adminGenerateCommand", () => {
  let tmp: string

  beforeEach(() => {
    tmp = mkdtempSync(join(tmpdir(), "voyant-cli-admin-generate-"))
  })

  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true })
  })

  it("fails when no config file is found", async () => {
    const { ctx, stderr } = makeCtx([], tmp)
    const code = await adminGenerateCommand(ctx)
    expect(code).toBe(1)
    expect(stderr.join("")).toContain("No voyant.config.* found")
  })

  it("writes the generated composition file with one factory per admin entry", async () => {
    writeFixture(tmp)
    const { ctx, stdout } = makeCtx([], tmp)
    const code = await adminGenerateCommand(ctx)
    expect(code).toBe(0)

    const outPath = join(tmp, "src", "admin.extensions.generated.ts")
    expect(existsSync(outPath)).toBe(true)
    const content = readFileSync(outPath, "utf8")
    expect(content).toContain("GENERATED by voyant admin generate — do not edit")
    expect(content).toContain(`import { createFooAdminExtension } from "@voyantjs/foo-react/admin"`)
    expect(content).toContain("export const generatedAdminExtensionFactories = {")
    expect(content).toContain("foo: createFooAdminExtension,")
    expect(content).toContain("} as const")
    expect(stdout.join("")).toContain("2 modules, 1 admin entries, wrote")
  })

  it("skips modules without an admin entry and notes them", async () => {
    writeFixture(tmp)
    const { ctx, stderr } = makeCtx([], tmp)
    await adminGenerateCommand(ctx)

    const content = readFileSync(join(tmp, "src", "admin.extensions.generated.ts"), "utf8")
    expect(content).not.toContain("@voyantjs/bar")
    expect(stderr.join("")).toContain("[admin-generate]")
    expect(stderr.join("")).toContain("@voyantjs/bar")
  })

  it("warns and skips when the admin entry lacks the conventional export", async () => {
    writeFixture(tmp)
    writeFileSync(
      join(tmp, "node_modules", "@voyantjs", "foo-react", "src", "admin", "index.tsx"),
      `export function createSomethingElse() {}\n`,
    )
    const { ctx, stderr } = makeCtx([], tmp)
    const code = await adminGenerateCommand(ctx)
    expect(code).toBe(0)

    const content = readFileSync(join(tmp, "src", "admin.extensions.generated.ts"), "utf8")
    expect(content).not.toContain("@voyantjs/foo-react/admin")
    expect(stderr.join("")).toContain("does not export createFooAdminExtension")
  })

  it("honors a package.json voyant.adminEntry override", async () => {
    writeFileSync(join(tmp, "voyant.config.ts"), `export default { modules: ["@voyantjs/baz"] }\n`)
    writePackage(tmp, "@voyantjs/baz", {
      exports: { ".": "./src/index.ts" },
      voyant: { adminEntry: "@voyantjs/baz-admin/entry" },
    })
    writePackage(
      tmp,
      "@voyantjs/baz-admin",
      { exports: { "./entry": "./src/entry.tsx" } },
      { "src/entry.tsx": `export function createBazAdminExtension() {}\n` },
    )

    const { ctx } = makeCtx([], tmp)
    const code = await adminGenerateCommand(ctx)
    expect(code).toBe(0)
    const content = readFileSync(join(tmp, "src", "admin.extensions.generated.ts"), "utf8")
    expect(content).toContain(`import { createBazAdminExtension } from "@voyantjs/baz-admin/entry"`)
    expect(content).toContain("baz: createBazAdminExtension,")
  })

  it("--check exits 1 when the file is missing", async () => {
    writeFixture(tmp)
    const { ctx, stderr } = makeCtx(["--check"], tmp)
    const code = await adminGenerateCommand(ctx)
    expect(code).toBe(1)
    expect(stderr.join("")).toContain("is missing")
    expect(existsSync(join(tmp, "src", "admin.extensions.generated.ts"))).toBe(false)
  })

  it("--check detects drift and passes once regenerated", async () => {
    writeFixture(tmp)
    mkdirSync(join(tmp, "src"), { recursive: true })
    writeFileSync(join(tmp, "src", "admin.extensions.generated.ts"), "// stale\n")

    const drift = makeCtx(["--check"], tmp)
    expect(await adminGenerateCommand(drift.ctx)).toBe(1)
    expect(drift.stderr.join("")).toContain("out of date")
    // --check must not rewrite the file.
    expect(readFileSync(join(tmp, "src", "admin.extensions.generated.ts"), "utf8")).toBe(
      "// stale\n",
    )

    expect(await adminGenerateCommand(makeCtx([], tmp).ctx)).toBe(0)
    const clean = makeCtx(["--check"], tmp)
    expect(await adminGenerateCommand(clean.ctx)).toBe(0)
    expect(clean.stdout.join("")).toContain("up to date")
  })

  it("respects --out relative to cwd", async () => {
    writeFixture(tmp)
    const { ctx } = makeCtx(["--out", "generated/admin.ts"], tmp)
    const code = await adminGenerateCommand(ctx)
    expect(code).toBe(0)
    expect(existsSync(join(tmp, "generated", "admin.ts"))).toBe(true)
  })
})

const FOO_ADMIN_ROUTES_SOURCE = `
import { defineAdminExtension } from "@voyantjs/admin"
import { FooPage, loadFooPage } from "../foo-page.js"

export function createFooAdminExtension(options = {}) {
  const { label = "Foo", path = "/foo" } = options
  return defineAdminExtension({
    id: "foo",
    routes: [
      {
        id: "foo-index",
        path,
        title: label,
        ssr: "data-only",
        component: FooPage,
        loader: ({ queryClient, runtime }) =>
          loadFooPage(queryClient, { baseUrl: runtime.baseUrl, fetcher: runtime.fetcher }),
      },
      {
        id: "foo-detail",
        path: \`\${path}/$fooId\`,
        title: label,
        component: FooDetailPage,
      },
      {
        id: "foo-metadata-only",
        path: "/foo-meta",
        title: label,
      },
    ],
  })
}
`

/** Fixture whose admin entry carries one zero-prop route implementation. */
function writeRoutesFixture(root: string) {
  writeFileSync(join(root, "voyant.config.ts"), `export default { modules: ["@voyantjs/foo"] }\n`)
  writePackage(root, "@voyantjs/foo", { exports: { ".": "./src/index.ts" } })
  writePackage(
    root,
    "@voyantjs/foo-react",
    { exports: { ".": "./src/index.ts", "./admin": "./src/admin/index.tsx" } },
    { "src/admin/index.tsx": FOO_ADMIN_ROUTES_SOURCE },
  )
}

describe("adminGenerateCommand --routes --files (legacy thin files)", () => {
  let tmp: string

  beforeEach(() => {
    tmp = mkdtempSync(join(tmpdir(), "voyant-cli-admin-routes-"))
  })

  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true })
  })

  const generatedPath = () => join(tmp, "src", "routes", "_workspace", "foo", "index.tsx")

  it("emits a generated thin route file for a zero-prop contribution only", async () => {
    writeRoutesFixture(tmp)
    const { ctx, stdout } = makeCtx(["--routes", "--files"], tmp)
    const code = await adminGenerateCommand(ctx)
    expect(code).toBe(0)

    const content = readFileSync(generatedPath(), "utf8")
    expect(content.startsWith("// GENERATED by voyant admin generate --routes")).toBe(true)
    expect(content).toContain(`import { requireAdminRoute } from "@voyantjs/admin"`)
    expect(content).toContain(`import { createFooAdminExtension } from "@voyantjs/foo-react/admin"`)
    expect(content).toContain(`import { getApiUrl } from "@/lib/env"`)
    expect(content).toContain(`import { operatorFetcher } from "@/lib/voyant-fetcher"`)
    expect(content).toContain(
      `const route = requireAdminRoute(createFooAdminExtension(), "foo-index")`,
    )
    expect(content).toContain(`createFileRoute("/_workspace/foo/")`)
    expect(content).toContain(`ssr: "data-only",`)
    expect(content).toContain(`component: RouteComponent,`)

    // The param-taking detail host and the metadata-only contribution are not emitted.
    expect(existsSync(join(tmp, "src", "routes", "_workspace", "foo", "$fooId.tsx"))).toBe(false)
    expect(existsSync(join(tmp, "src", "routes", "_workspace", "foo-meta"))).toBe(false)
    expect(stdout.join("")).toContain(
      "1 param route(s) and 1 metadata-only contribution(s) left to hand-written hosts",
    )
    expect(stdout.join("")).toContain("1 written")
  })

  it("honors the manifest admin.routes runtime-import config", async () => {
    writeRoutesFixture(tmp)
    writeFileSync(
      join(tmp, "voyant.config.ts"),
      [
        `export default {`,
        `  modules: ["@voyantjs/foo"],`,
        `  admin: {`,
        `    routes: {`,
        `      apiUrlModule: "~/runtime/env",`,
        `      apiUrlExport: "apiUrl",`,
        `      fetcherModule: "~/runtime/fetch",`,
        `      fetcherExport: "appFetcher",`,
        `    },`,
        `  },`,
        `}`,
        ``,
      ].join("\n"),
    )
    const { ctx } = makeCtx(["--routes", "--files"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
    const content = readFileSync(generatedPath(), "utf8")
    expect(content).toContain(`import { apiUrl } from "~/runtime/env"`)
    expect(content).toContain(`import { appFetcher } from "~/runtime/fetch"`)
    expect(content).toContain(`runtime: { baseUrl: apiUrl(), fetcher: appFetcher },`)
  })

  it("never overwrites a hand-written file lacking the generated header (ejection)", async () => {
    writeRoutesFixture(tmp)
    mkdirSync(join(tmp, "src", "routes", "_workspace", "foo"), { recursive: true })
    const handWritten = `// hand-written host\nexport const Route = {}\n`
    writeFileSync(generatedPath(), handWritten)

    const { ctx, stderr, stdout } = makeCtx(["--routes", "--files"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
    expect(readFileSync(generatedPath(), "utf8")).toBe(handWritten)
    expect(stderr.join("")).toContain("ejected, hand-written host")
    expect(stdout.join("")).toContain("1 ejected")
  })

  it("skips when a hand-written host exists under another file-routing spelling", async () => {
    writeRoutesFixture(tmp)
    mkdirSync(join(tmp, "src", "routes", "_workspace"), { recursive: true })
    writeFileSync(
      join(tmp, "src", "routes", "_workspace", "foo.tsx"),
      `// flat hand-written host\n`,
    )

    const { ctx, stderr } = makeCtx(["--routes", "--files"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
    expect(existsSync(generatedPath())).toBe(false)
    expect(stderr.join("")).toContain("already binds this route")
  })

  it("--check reports drift for missing and stale files, passes when regenerated", async () => {
    writeRoutesFixture(tmp)

    const missing = makeCtx(["--routes", "--files", "--check"], tmp)
    expect(await adminGenerateCommand(missing.ctx)).toBe(1)
    expect(missing.stderr.join("")).toContain("is missing")
    expect(existsSync(generatedPath())).toBe(false)

    expect(await adminGenerateCommand(makeCtx(["--routes", "--files"], tmp).ctx)).toBe(0)
    const clean = makeCtx(["--routes", "--files", "--check"], tmp)
    expect(await adminGenerateCommand(clean.ctx)).toBe(0)
    expect(clean.stdout.join("")).toContain("1 up to date")

    writeFileSync(
      generatedPath(),
      `// GENERATED by voyant admin generate --routes — do not edit.\n// stale\n`,
    )
    const drift = makeCtx(["--routes", "--files", "--check"], tmp)
    expect(await adminGenerateCommand(drift.ctx)).toBe(1)
    expect(drift.stderr.join("")).toContain("is out of date")
  })

  it("--check treats ejected files as fine", async () => {
    writeRoutesFixture(tmp)
    mkdirSync(join(tmp, "src", "routes", "_workspace", "foo"), { recursive: true })
    writeFileSync(generatedPath(), `// hand-written host\n`)
    const { ctx } = makeCtx(["--routes", "--files", "--check"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
  })

  it("respects --routes-dir", async () => {
    writeRoutesFixture(tmp)
    const { ctx } = makeCtx(["--routes", "--files", "--routes-dir", "app/routes/admin"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
    const content = readFileSync(join(tmp, "app", "routes", "admin", "foo", "index.tsx"), "utf8")
    expect(content).toContain(`createFileRoute("/admin/foo/")`)
  })
})

const FOO_ADMIN_MODULE_SOURCE = `
import { defineAdminExtension } from "@voyantjs/admin"
import { z } from "zod"

export const fooSearchSchema = z.object({ tab: z.string().optional() })

export function createFooAdminExtension(options = {}) {
  const { label = "Foo", basePath = "/foo" } = options
  return defineAdminExtension({
    id: "foo",
    routes: [
      {
        id: "foo-index",
        path: basePath,
        title: label,
        ssr: "data-only",
        validateSearch: (search) => fooSearchSchema.parse(search),
        // Lazy page module on purpose (packaged-admin RFC §4.8).
        page: () => import("./pages/foo-index.js"),
      },
      {
        id: "foo-detail",
        path: \`\${basePath}/$fooId\`,
        title: label,
        page: () => import("./pages/foo-detail.js"),
      },
      {
        id: "foo-meta",
        path: "/foo-meta",
        title: label,
      },
    ],
  })
}
`

/** Fixture whose admin entry carries §4.8 contributions (page + $param + metadata). */
function writeModuleFixture(root: string) {
  writeFileSync(join(root, "voyant.config.ts"), `export default { modules: ["@voyantjs/foo"] }\n`)
  writePackage(root, "@voyantjs/foo", { exports: { ".": "./src/index.ts" } })
  writePackage(
    root,
    "@voyantjs/foo-react",
    { exports: { ".": "./src/index.ts", "./admin": "./src/admin/index.tsx" } },
    { "src/admin/index.tsx": FOO_ADMIN_MODULE_SOURCE },
  )
}

describe("adminGenerateCommand --routes (code-assembled module)", () => {
  let tmp: string

  beforeEach(() => {
    tmp = mkdtempSync(join(tmpdir(), "voyant-cli-admin-routes-module-"))
  })

  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true })
  })

  const modulePath = () => join(tmp, "src", "admin.routes.generated.tsx")

  const METADATA_ONLY_SOURCE = `
export function createFooAdminExtension(options = {}) {
  return { id: "foo", routes: [{ id: "foo-meta", path: "/foo-meta", title: "Meta" }] }
}
`

  it("removes a stale generated module when no implemented contributions remain", async () => {
    writeModuleFixture(tmp)
    expect(await adminGenerateCommand(makeCtx(["--routes"], tmp).ctx)).toBe(0)
    expect(readFileSync(modulePath(), "utf8")).toContain("FooIndexRoute")

    // The module's admin entry drops to metadata-only contributions.
    writeFileSync(
      join(tmp, "node_modules", "@voyantjs", "foo-react", "src", "admin", "index.tsx"),
      METADATA_ONLY_SOURCE,
    )

    const check = makeCtx(["--routes", "--check"], tmp)
    expect(await adminGenerateCommand(check.ctx)).toBe(1)
    expect(check.stderr.join("")).toContain("is stale — no implemented extension")

    const write = makeCtx(["--routes"], tmp)
    expect(await adminGenerateCommand(write.ctx)).toBe(0)
    expect(write.stdout.join("")).toContain("removed src/admin.routes.generated.tsx")
    expect(existsSync(modulePath())).toBe(false)
  })

  it("leaves an ejected module in place at zero implemented contributions", async () => {
    writeModuleFixture(tmp)
    expect(await adminGenerateCommand(makeCtx(["--routes"], tmp).ctx)).toBe(0)
    const ejected = readFileSync(modulePath(), "utf8").split("\n").slice(6).join("\n")
    writeFileSync(modulePath(), ejected)
    writeFileSync(
      join(tmp, "node_modules", "@voyantjs", "foo-react", "src", "admin", "index.tsx"),
      METADATA_ONLY_SOURCE,
    )

    const { ctx, stderr } = makeCtx(["--routes"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
    expect(stderr.join("")).toContain("no generated header (ejected, host-owned)")
    expect(existsSync(modulePath())).toBe(true)
  })

  it("derives the workspace alias from an absolute routes dir inside the project", async () => {
    writeModuleFixture(tmp)
    const { ctx } = makeCtx(
      ["--routes", "--routes-dir", join(tmp, "src", "routes", "_workspace")],
      tmp,
    )
    expect(await adminGenerateCommand(ctx)).toBe(0)
    expect(readFileSync(modulePath(), "utf8")).toContain(
      `import { Route as WorkspaceRoute } from "@/routes/_workspace/route"`,
    )
  })

  it("errors when an absolute routes dir resolves outside the project root", async () => {
    writeModuleFixture(tmp)
    const outside = mkdtempSync(join(tmpdir(), "voyant-cli-outside-"))
    try {
      const { ctx, stderr } = makeCtx(["--routes", "--routes-dir", outside], tmp)
      expect(await adminGenerateCommand(ctx)).toBe(1)
      expect(stderr.join("")).toContain("resolves outside the project root")
    } finally {
      rmSync(outside, { recursive: true, force: true })
    }
  })

  it("emits one code-assembled module — param routes included, metadata-only skipped", async () => {
    writeModuleFixture(tmp)
    const { ctx, stdout } = makeCtx(["--routes"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)

    const content = readFileSync(modulePath(), "utf8")
    expect(
      content.startsWith("// GENERATED by voyant admin generate --routes — do not edit."),
    ).toBe(true)
    expect(content).toContain(`import { createRoute } from "@tanstack/react-router"`)
    expect(content).toContain(`import { adminExtensionRouteOptions } from "@voyantjs/admin-app"`)
    expect(content).toContain(`import { fooSearchSchema } from "@voyantjs/foo-react/admin"`)
    expect(content).toContain(`import { adminExtensions } from "@/lib/admin-extensions"`)
    expect(content).toContain(`import { Route as WorkspaceRoute } from "@/routes/_workspace/route"`)
    expect(content).toContain(`const fooExtension = extension("foo")`)
    expect(content).toContain("export const FooIndexRoute = createRoute({")
    expect(content).toContain("  validateSearch: fooSearchSchema,")
    expect(content).toContain(
      `  ...adminExtensionRouteOptions(fooExtension, "foo-index", runtime),`,
    )
    // The param-taking detail route is code-assembled too — no host file needed.
    expect(content).toContain("export const FooDetailRoute = createRoute({")
    expect(content).toContain(`  path: "/foo/$fooId",`)
    // The metadata-only contribution stays out of the module.
    expect(content).not.toContain("/foo-meta")
    expect(content).toContain(`  "/foo/$fooId": typeof FooDetailRoute`)
    expect(content).toContain(`  "/_workspace/foo/$fooId": typeof FooDetailRoute`)
    expect(content).toContain(`[admin.routes.generated] No registered admin extension "\${id}".`)
    // No per-route files are written.
    expect(existsSync(join(tmp, "src", "routes"))).toBe(false)
    expect(stdout.join("")).toContain("2 extension route(s) across 1 extension(s)")
    expect(stdout.join("")).toContain("1 metadata-only contribution(s)")
  })

  it("--check reports missing and drift, passes once regenerated", async () => {
    writeModuleFixture(tmp)

    const missing = makeCtx(["--routes", "--check"], tmp)
    expect(await adminGenerateCommand(missing.ctx)).toBe(1)
    expect(missing.stderr.join("")).toContain("is missing")
    expect(existsSync(modulePath())).toBe(false)

    expect(await adminGenerateCommand(makeCtx(["--routes"], tmp).ctx)).toBe(0)
    const clean = makeCtx(["--routes", "--check"], tmp)
    expect(await adminGenerateCommand(clean.ctx)).toBe(0)
    expect(clean.stdout.join("")).toContain("is up to date")

    writeFileSync(
      modulePath(),
      `// GENERATED by voyant admin generate --routes — do not edit.\n// stale\n`,
    )
    const drift = makeCtx(["--routes", "--check"], tmp)
    expect(await adminGenerateCommand(drift.ctx)).toBe(1)
    expect(drift.stderr.join("")).toContain("is out of date")
  })

  it("never overwrites a host-owned module lacking the generated header", async () => {
    writeModuleFixture(tmp)
    mkdirSync(join(tmp, "src"), { recursive: true })
    const handWritten = `// hand-written admin routes\nexport const adminExtensionRoutes = []\n`
    writeFileSync(modulePath(), handWritten)

    const write = makeCtx(["--routes"], tmp)
    expect(await adminGenerateCommand(write.ctx)).toBe(0)
    expect(readFileSync(modulePath(), "utf8")).toBe(handWritten)
    expect(write.stderr.join("")).toContain("no generated header (ejected, host-owned)")

    // --check treats the ejected module as fine.
    const check = makeCtx(["--routes", "--check"], tmp)
    expect(await adminGenerateCommand(check.ctx)).toBe(0)
  })

  it("ejects a single route bound by a hand-written route file", async () => {
    writeModuleFixture(tmp)
    mkdirSync(join(tmp, "src", "routes", "_workspace", "foo"), { recursive: true })
    writeFileSync(
      join(tmp, "src", "routes", "_workspace", "foo", "index.tsx"),
      `// hand-written host\nexport const Route = {}\n`,
    )

    const { ctx, stderr, stdout } = makeCtx(["--routes"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
    const content = readFileSync(modulePath(), "utf8")
    expect(content).not.toContain(`path: "/foo",`)
    expect(content).toContain(`path: "/foo/$fooId",`)
    expect(stderr.join("")).toContain("binds this route (ejected)")
    expect(stdout.join("")).toContain("1 ejected")
  })

  it("removes superseded generated thin route files, and flags them with --check", async () => {
    writeModuleFixture(tmp)
    const thinFile = join(tmp, "src", "routes", "_workspace", "foo", "index.tsx")
    mkdirSync(join(thinFile, ".."), { recursive: true })
    const thinContent = `// GENERATED by voyant admin generate --routes — do not edit.\n// thin host\n`
    writeFileSync(thinFile, thinContent)

    expect(await adminGenerateCommand(makeCtx(["--routes"], tmp).ctx)).toBe(0)
    expect(existsSync(thinFile)).toBe(false)
    expect(readFileSync(modulePath(), "utf8")).toContain(`path: "/foo",`)

    writeFileSync(thinFile, thinContent)
    const check = makeCtx(["--routes", "--check"], tmp)
    expect(await adminGenerateCommand(check.ctx)).toBe(1)
    expect(check.stderr.join("")).toContain("superseded")
  })

  it("honors --routes-dir for the id prefix and the workspace route import", async () => {
    writeModuleFixture(tmp)
    const { ctx } = makeCtx(["--routes", "--routes-dir", "app/routes/admin"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
    const content = readFileSync(modulePath(), "utf8")
    expect(content).toContain(`import { Route as WorkspaceRoute } from "@/app/routes/admin/route"`)
    expect(content).toContain(`  "/admin/foo/$fooId": typeof FooDetailRoute`)
  })

  it("honors the manifest admin.routes import + out config", async () => {
    writeModuleFixture(tmp)
    writeFileSync(
      join(tmp, "voyant.config.ts"),
      [
        `export default {`,
        `  modules: ["@voyantjs/foo"],`,
        `  admin: {`,
        `    routes: {`,
        `      out: "src/admin-routes.gen.tsx",`,
        `      registryModule: "~/admin/registry",`,
        `      registryExport: "registry",`,
        `      apiUrlModule: "~/runtime/env",`,
        `      apiUrlExport: "apiUrl",`,
        `      fetcherModule: "~/runtime/fetch",`,
        `      fetcherExport: "appFetcher",`,
        `      workspaceRouteModule: "~/routes/workspace",`,
        `    },`,
        `  },`,
        `}`,
        ``,
      ].join("\n"),
    )
    const { ctx } = makeCtx(["--routes"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
    const content = readFileSync(join(tmp, "src", "admin-routes.gen.tsx"), "utf8")
    expect(content).toContain(`import { registry } from "~/admin/registry"`)
    expect(content).toContain(`import { Route as WorkspaceRoute } from "~/routes/workspace"`)
    expect(content).toContain("const runtime = () => ({ baseUrl: apiUrl(), fetcher: appFetcher })")
    expect(content).toContain("const match = registry.find((candidate) => candidate.id === id)")
    expect(content).toContain(`[admin-routes.gen] No registered admin extension "\${id}".`)
  })

  it("notes contributions whose validateSearch schema is not an export", async () => {
    writeModuleFixture(tmp)
    writeFileSync(
      join(tmp, "node_modules", "@voyantjs", "foo-react", "src", "admin", "index.tsx"),
      FOO_ADMIN_MODULE_SOURCE.replace(
        "validateSearch: (search) => fooSearchSchema.parse(search),",
        "validateSearch: (search) => privateSchema.parse(search),",
      ),
    )
    const { ctx, stderr } = makeCtx(["--routes"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
    const content = readFileSync(modulePath(), "utf8")
    expect(content).not.toContain("validateSearch:")
    expect(stderr.join("")).toContain("emitted without a typed search contract")
  })
})

// ---------------------------------------------------------------------------
// Redirects, nested children, and the built-in core entry (RFC #1643 sweep)
// ---------------------------------------------------------------------------

const REDIRECT_AND_CHILDREN_SOURCE = `
import { defineAdminExtension } from "@voyantjs/admin"

export function createFooAdminExtension(options = {}) {
  const { basePath = "/foo" } = options
  return defineAdminExtension({
    id: "foo",
    routes: [
      {
        id: "foo-index",
        path: basePath,
        title: "Foo",
        redirectTo: \`\${basePath}/items\`,
      },
      {
        id: "foo-items",
        path: \`\${basePath}/items\`,
        title: "Items",
        page: () => import("./pages/items.js"),
      },
      {
        id: "foo-area",
        path: "/foo-area",
        title: "Area",
        page: () => import("./pages/area-layout.js"),
        children: [
          { id: "foo-area-index", path: "/", title: "Area", redirectTo: "/foo-area/one" },
          { id: "foo-area-one", path: "/one", title: "One", page: () => import("./pages/one.js") },
          ...options.extraPages ?? [],
        ],
      },
    ],
  })
}
`

/** Imperative factory shape — the scanner cannot read it; the CLI's built-in table applies. */
const CORE_EXTENSION_SOURCE = `
export function createAdminCoreExtension(options = {}) {
  const routes = []
  routes.push({ id: "core-dashboard", path: "/" })
  return { id: "core", routes }
}
`

function writeCorePackage(root: string, withCoreExtension = true) {
  writePackage(
    root,
    "@voyantjs/admin-app",
    {
      exports: withCoreExtension
        ? { ".": "./src/index.ts", "./core-extension": "./src/core-extension/index.tsx" }
        : { ".": "./src/index.ts" },
    },
    withCoreExtension ? { "src/core-extension/index.tsx": CORE_EXTENSION_SOURCE } : {},
  )
}

describe("adminGenerateCommand --routes — redirects + nested children", () => {
  let tmp: string

  beforeEach(() => {
    tmp = mkdtempSync(join(tmpdir(), "voyant-cli-admin-routes-nested-"))
    writeFileSync(join(tmp, "voyant.config.ts"), `export default { modules: ["@voyantjs/foo"] }\n`)
    writePackage(tmp, "@voyantjs/foo", { exports: { ".": "./src/index.ts" } })
    writePackage(
      tmp,
      "@voyantjs/foo-react",
      { exports: { ".": "./src/index.ts", "./admin": "./src/admin/index.tsx" } },
      { "src/admin/index.tsx": REDIRECT_AND_CHILDREN_SOURCE },
    )
  })

  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true })
  })

  const modulePath = () => join(tmp, "src", "admin.routes.generated.tsx")

  it("emits redirect-only contributions as plain routes (implemented on their own)", async () => {
    const { ctx, stdout } = makeCtx(["--routes"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
    const content = readFileSync(modulePath(), "utf8")
    expect(content).toContain(
      [
        "export const FooIndexRoute = createRoute({",
        "  getParentRoute: workspace,",
        `  path: "/foo",`,
        `  ...adminExtensionRouteOptions(fooExtension, "foo-index", runtime),`,
        "})",
      ].join("\n"),
    )
    // Redirect leaves get plain typed-link keys in all three maps.
    expect(content).toContain(`  "/foo": typeof FooIndexRoute`)
    expect(content).toContain(`  "/_workspace/foo": typeof FooIndexRoute`)
    // 1 redirect + 1 page + 1 layout parent + 2 static children = 5.
    expect(stdout.join("")).toContain("5 extension route(s)")
  })

  it("emits a scanned children subtree with the generic comment and exclude list", async () => {
    const { ctx } = makeCtx(["--routes"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
    const content = readFileSync(modulePath(), "utf8")
    expect(content).toContain("const fooArea = () => FooAreaRoute")
    expect(content).toContain(
      [
        "export const FooAreaIndexRoute = createRoute({",
        "  getParentRoute: fooArea,",
        `  path: "/",`,
        `  ...adminExtensionRouteOptions(fooExtension, "foo-area-index", runtime),`,
        "})",
      ].join("\n"),
    )
    expect(content).toContain("// foo-area subtree: the static children above keep literal paths")
    expect(content).toContain("export const FooAreaRouteWithChildren = FooAreaRoute.addChildren([")
    expect(content).toContain(
      [
        `  ...adminExtensionChildRoutes(fooExtension, "foo-area", fooArea, runtime, {`,
        "    exclude: [",
        `      "/",`,
        `      "/one",`,
        "    ],",
        "  }),",
        "])",
      ].join("\n"),
    )
    // Maps: parent → WithChildren (FullPath/Id), index child claims the
    // parent key in ByTo and the trailing-slash key in ByFullPath.
    expect(content).toContain(`  "/foo-area": typeof FooAreaRouteWithChildren`)
    expect(content).toContain(`  "/foo-area/": typeof FooAreaIndexRoute`)
    expect(content).toContain(`  "/foo-area": typeof FooAreaIndexRoute`)
    expect(content).toContain(`  "/foo-area/one": typeof FooAreaOneRoute`)
    expect(content).toContain(`  "/_workspace/foo-area/": typeof FooAreaIndexRoute`)
    // The runtime-only spread children never appear.
    expect(content).not.toContain("extraPages")
    // Tree array references the WithChildren const, children stay out.
    expect(content).toContain("  FooAreaRouteWithChildren,")
    expect(content).not.toContain("\n  FooAreaIndexRoute,\n  FooAreaOneRoute,\n]")
  })

  it("--check round-trips the nested emission", async () => {
    expect(await adminGenerateCommand(makeCtx(["--routes"], tmp).ctx)).toBe(0)
    const clean = makeCtx(["--routes", "--check"], tmp)
    expect(await adminGenerateCommand(clean.ctx)).toBe(0)
    expect(clean.stdout.join("")).toContain("is up to date")
  })
})

describe("adminGenerateCommand --routes — built-in core entry", () => {
  let tmp: string

  beforeEach(() => {
    tmp = mkdtempSync(join(tmpdir(), "voyant-cli-admin-routes-core-"))
    writeModuleFixture(tmp)
  })

  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true })
  })

  const modulePath = () => join(tmp, "src", "admin.routes.generated.tsx")

  it("includes the core section when @voyantjs/admin-app exposes ./core-extension", async () => {
    writeCorePackage(tmp)
    const { ctx, stderr, stdout } = makeCtx(["--routes"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
    expect(stderr.join("")).not.toContain("built-in core entry skipped")

    const content = readFileSync(modulePath(), "utf8")
    expect(content).toContain(
      `import { adminExtensionChildRoutes, adminExtensionRouteOptions } from "@voyantjs/admin-app"`,
    )
    expect(content).toContain(`const coreExtension = extension("core")`)
    expect(content).toContain(
      [
        "export const CoreDashboardRoute = createRoute({",
        "  getParentRoute: workspace,",
        `  path: "/",`,
        `  ...adminExtensionRouteOptions(coreExtension, "core-dashboard", runtime),`,
        "})",
      ].join("\n"),
    )
    // The settings subtree carries the core-specific comment and the full
    // built-in exclude list.
    expect(content).toContain(
      [
        "// Settings subtree: the static children above keep literal paths for typed",
        "// links; app-supplied extra settings pages (factory `settings.extraPages`,",
        "// invisible to the generator) bind at runtime via adminExtensionChildRoutes.",
        "export const CoreSettingsRouteWithChildren = CoreSettingsRoute.addChildren([",
      ].join("\n"),
    )
    expect(content).toContain(
      `  ...adminExtensionChildRoutes(coreExtension, "core-settings", coreSettings, runtime, {`,
    )
    expect(content).toContain(`      "/product-tags",`)
    expect(content).toContain(`  "/settings/product-tags": typeof CoreSettingsProductTagsRoute`)
    expect(content).toContain(`  "/_workspace/settings/": typeof CoreSettingsIndexRoute`)
    // Alphabetical section sort: core lands between the manifest sections.
    expect(content.indexOf(`extension("core")`)).toBeGreaterThan(-1)
    expect(content.indexOf(`extension("core")`)).toBeLessThan(content.indexOf(`extension("foo")`))
    // 2 foo + core (3 top-level + 10 settings children) = 15.
    expect(stdout.join("")).toContain("15 extension route(s) across 2 extension(s)")
  })

  it("skips the core entry when admin-app lacks the ./core-extension export", async () => {
    writeCorePackage(tmp, false)
    const { ctx, stderr } = makeCtx(["--routes"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
    expect(stderr.join("")).toContain("built-in core entry skipped")
    const content = readFileSync(modulePath(), "utf8")
    expect(content).not.toContain(`extension("core")`)
    expect(content).toContain(`import { adminExtensionRouteOptions } from "@voyantjs/admin-app"`)
  })

  it("skips the core entry when admin-app is not resolvable at all", async () => {
    const { ctx, stderr } = makeCtx(["--routes"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
    expect(stderr.join("")).toContain("built-in core entry skipped")
    expect(readFileSync(modulePath(), "utf8")).not.toContain(`extension("core")`)
  })

  it("warns when the resolved core entry lacks the factory export", async () => {
    writePackage(
      tmp,
      "@voyantjs/admin-app",
      { exports: { "./core-extension": "./src/core-extension/index.tsx" } },
      { "src/core-extension/index.tsx": `export function createSomethingElse() {}\n` },
    )
    const { ctx, stderr } = makeCtx(["--routes"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
    expect(stderr.join("")).toContain("does not export createAdminCoreExtension")
    // Still emitted — the warning is best-effort, mirroring scanAdminEntries.
    expect(readFileSync(modulePath(), "utf8")).toContain(`extension("core")`)
  })
})

describe("adminGenerateCommand --routes --files — redirect/children skip (legacy)", () => {
  let tmp: string

  beforeEach(() => {
    tmp = mkdtempSync(join(tmpdir(), "voyant-cli-admin-files-skip-"))
    writeFileSync(join(tmp, "voyant.config.ts"), `export default { modules: ["@voyantjs/foo"] }\n`)
    writePackage(tmp, "@voyantjs/foo", { exports: { ".": "./src/index.ts" } })
    writePackage(
      tmp,
      "@voyantjs/foo-react",
      { exports: { ".": "./src/index.ts", "./admin": "./src/admin/index.tsx" } },
      {
        "src/admin/index.tsx": `
export function createFooAdminExtension(options = {}) {
  return {
    id: "foo",
    routes: [
      { id: "foo-redirect", path: "/foo", title: "Foo", redirectTo: "/foo/items", component: FooHost },
      {
        id: "foo-area",
        path: "/foo-area",
        title: "Area",
        component: AreaLayout,
        children: [{ id: "foo-area-one", path: "/one", title: "One", component: One }],
      },
      { id: "foo-plain", path: "/foo-plain", title: "Plain", component: Plain },
    ],
  }
}
`,
      },
    )
    // Core resolvable too — the legacy mode must ignore it entirely.
    writeCorePackage(tmp)
  })

  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true })
  })

  it("skips redirect and children contributions even when they carry components", async () => {
    const { ctx, stdout } = makeCtx(["--routes", "--files"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)

    const workspaceDir = join(tmp, "src", "routes", "_workspace")
    expect(existsSync(join(workspaceDir, "foo-plain", "index.tsx"))).toBe(true)
    expect(existsSync(join(workspaceDir, "foo"))).toBe(false)
    expect(existsSync(join(workspaceDir, "foo-area"))).toBe(false)
    // The built-in core entry never emits thin files.
    expect(existsSync(join(workspaceDir, "settings"))).toBe(false)
    expect(existsSync(join(workspaceDir, "account"))).toBe(false)
    expect(stdout.join("")).toContain("1 written")
    expect(stdout.join("")).toContain(
      "2 redirect/children contribution(s) left to the code-assembled module",
    )
  })
})

describe("adminGenerateCommand --destinations (generated resolver map, RFC §4.7)", () => {
  let tmp: string

  beforeEach(() => {
    tmp = mkdtempSync(join(tmpdir(), "voyant-cli-admin-generate-destinations-"))
  })

  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true })
  })

  const ANNOTATED_SOURCE = `
declare module "@voyantjs/admin" {
  interface AdminDestinations {
    "foo.list": Record<string, never>
    "foo.detail": { fooId: string }
  }
}
export function createFooAdminExtension(options = {}) {
  const { basePath = "/foo" } = options
  return defineAdminExtension({
    id: "foo",
    routes: [
      {
        id: "foo-index",
        path: basePath,
        title: "Foo",
        destination: "foo.list",
        page: () => import("./foo-host.js"),
      },
      {
        id: "foo-detail",
        path: \`\${basePath}/$id\`,
        title: "Foo",
        destination: "foo.detail",
        destinationParams: { id: "fooId" },
        page: () => import("./pages/foo-detail-page.js"),
      },
    ],
  })
}
`

  function writeAnnotatedFixture(root: string, source = ANNOTATED_SOURCE) {
    writeFileSync(join(root, "voyant.config.ts"), `export default { modules: ["@voyantjs/foo"] }\n`)
    writePackage(root, "@voyantjs/foo", { exports: { ".": "./src/index.ts" } })
    writePackage(
      root,
      "@voyantjs/foo-react",
      { exports: { ".": "./src/index.ts", "./admin": "./src/admin/index.tsx" } },
      { "src/admin/index.tsx": source },
    )
  }

  it("writes the generated destinations module with one resolver per annotation", async () => {
    writeAnnotatedFixture(tmp)
    const { ctx, stdout } = makeCtx(["--destinations"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)

    const outPath = join(tmp, "src", "admin.destinations.generated.ts")
    expect(existsSync(outPath)).toBe(true)
    const content = readFileSync(outPath, "utf8")
    expect(content.startsWith("// GENERATED by voyant admin generate --destinations")).toBe(true)
    expect(content).toContain(`import type {} from "@voyantjs/foo-react/admin"`)
    expect(content).toContain(`"foo.list": () => "/foo",`)
    // biome-ignore lint/suspicious/noTemplateCurlyInString: asserting emitted template-literal source
    expect(content).toContain('"foo.detail": ({ fooId }) => `/foo/${encodeURIComponent(fooId)}`,')
    expect(content).toContain("} satisfies Partial<AdminDestinationResolvers>")
    expect(stdout.join("")).toContain(
      "destinations: 2 route-backed resolver(s) across 1 admin entries",
    )
  })

  it("honors --out and is idempotent", async () => {
    writeAnnotatedFixture(tmp)
    const outPath = join(tmp, "src", "nav", "destinations.generated.ts")
    expect(await adminGenerateCommand(makeCtx(["--destinations", "--out", outPath], tmp).ctx)).toBe(
      0,
    )
    const first = readFileSync(outPath, "utf8")
    const again = makeCtx(["--destinations", "--out", outPath], tmp)
    expect(await adminGenerateCommand(again.ctx)).toBe(0)
    expect(again.stdout.join("")).toContain("is up to date")
    expect(readFileSync(outPath, "utf8")).toBe(first)
  })

  it("--check exits 1 when the module is missing and when it drifts", async () => {
    writeAnnotatedFixture(tmp)
    const missing = makeCtx(["--destinations", "--check"], tmp)
    expect(await adminGenerateCommand(missing.ctx)).toBe(1)
    expect(missing.stderr.join("")).toContain(
      "is missing — run `voyant admin generate --destinations`",
    )

    expect(await adminGenerateCommand(makeCtx(["--destinations"], tmp).ctx)).toBe(0)
    const clean = makeCtx(["--destinations", "--check"], tmp)
    expect(await adminGenerateCommand(clean.ctx)).toBe(0)

    // A changed param mapping in the package drifts the committed module.
    writeAnnotatedFixture(tmp, ANNOTATED_SOURCE.replace(`destinationParams: { id: "fooId" },`, ""))
    const drifted = makeCtx(["--destinations", "--check"], tmp)
    expect(await adminGenerateCommand(drifted.ctx)).toBe(1)
    expect(drifted.stderr.join("")).toContain("is out of date")
  })

  it("never overwrites an ejected module (no generated header)", async () => {
    writeAnnotatedFixture(tmp)
    mkdirSync(join(tmp, "src"), { recursive: true })
    const outPath = join(tmp, "src", "admin.destinations.generated.ts")
    const ejected = `// host-owned\nexport const generatedAdminDestinations = {}\n`
    writeFileSync(outPath, ejected)
    const { ctx, stderr } = makeCtx(["--destinations"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
    expect(stderr.join("")).toContain("no generated header (ejected, host-owned)")
    expect(readFileSync(outPath, "utf8")).toBe(ejected)
  })

  it("removes a stale generated module when no annotations remain", async () => {
    writeAnnotatedFixture(tmp)
    expect(await adminGenerateCommand(makeCtx(["--destinations"], tmp).ctx)).toBe(0)
    const outPath = join(tmp, "src", "admin.destinations.generated.ts")

    // Annotations vanish from the package.
    writeAnnotatedFixture(
      tmp,
      `export function createFooAdminExtension() { return { id: "foo", routes: [{ id: "foo-index", path: "/foo" }] } }`,
    )
    const check = makeCtx(["--destinations", "--check"], tmp)
    expect(await adminGenerateCommand(check.ctx)).toBe(1)
    expect(check.stderr.join("")).toContain(
      "is stale — no route-backed destination annotations remain",
    )

    const write = makeCtx(["--destinations"], tmp)
    expect(await adminGenerateCommand(write.ctx)).toBe(0)
    expect(write.stdout.join("")).toContain("removed")
    expect(existsSync(outPath)).toBe(false)

    // Converged: nothing to emit, exit 0.
    const converged = makeCtx(["--destinations", "--check"], tmp)
    expect(await adminGenerateCommand(converged.ctx)).toBe(0)
    expect(converged.stdout.join("")).toContain("nothing to emit")
  })

  it("notes skipped annotations whose path is not statically resolvable", async () => {
    writeAnnotatedFixture(
      tmp,
      `
export function createFooAdminExtension(options = {}) {
  return defineAdminExtension({
    id: "foo",
    routes: [
      { id: "foo-index", path: options.weird, title: "Foo", destination: "foo.list" },
      { id: "foo-detail", path: "/foo/$id", title: "Foo", destination: "foo.detail" },
    ],
  })
}
`,
    )
    const { ctx, stderr } = makeCtx(["--destinations"], tmp)
    expect(await adminGenerateCommand(ctx)).toBe(0)
    expect(stderr.join("")).toContain('skipped destination "foo.list"')
    const content = readFileSync(join(tmp, "src", "admin.destinations.generated.ts"), "utf8")
    expect(content).not.toContain('"foo.list"')
    // Unmapped param keeps its route name.
    // biome-ignore lint/suspicious/noTemplateCurlyInString: asserting emitted template-literal source
    expect(content).toContain('"foo.detail": ({ id }) => `/foo/${encodeURIComponent(id)}`,')
  })
})
